--SLO Analysis (Afia Rizavi)
--Azhar Ali Khan
--21st June 2013

--Locking Base
--SLO subscribers on the given dates

SEL file_dt,COUNT(distinct accs_meth_id)subs FROM  dp_tmp_rep.aak_slo_base GROUP BY 1
SEL * FROM dp_tmp_rep.asp_sloreq_base WHERE accs_meth_id = 13654614
SEL file_dt,COUNT (DISTINCT accs_meth_id) FROM  dp_tmp_rep.aak_slo_base group by 1
CREATE  TABLE dp_tmp_rep.aak_slo_base
AS
(
SEL
accs_meth_id
,file_dt
FROM sel top 10 * from DP_MDM_VEW.adhoc_msisdn_load 
WHERE campaign_file_desc = 'CAMP_SIM_LAGAO_DAILY'
AND file_dt between '2013-05-31' and CURRENT_DATE -1
GROUP BY 1,2
)
WITH DATA PRIMARY INDEX (accs_meth_id)

--Fetching Priceplan on Subscription Date
sel ACCS_METH_ID from dp_tmp_rep.aak_slo_base where accs_meth_id not in ( sel accs_meth_id from dp_tmp_rep.aak_slo_pp group by 1) and file_dt = '2013-05-31' group by 1
sel * from DP_VEW.CALL_HIST where Accs_Meth_Id = 194907459 and call_start_dt between '2013-05-31' and CURRENT_DATE -1


SEL offering_id, file_dt, COUNT( ACCS_METH_ID)subs FROM dp_tmp_rep.aak_slo_pp group by 1,2 order by 1,2
drop table dp_tmp_rep.aak_slo_pp;
CREATE  TABLE dp_tmp_rep.aak_slo_pp
AS
(
SEL
a.accs_meth_id
,file_dt
,offering_id
FROM dp_mdm_vew.adhoc_msisdn_load a
LEFT JOIN call_hist b
ON a.accs_meth_id = b.accs_meth_id
--AND a.file_dt = b.call_start_dt
WHERE campaign_file_desc = 'CAMP_SIM_LAGAO_DAILY'
AND call_start_dt between '2013-05-31' and CURRENT_DATE -1
QUALIFY ROW_NUMBER() OVER(PARTITION BY b.accs_meth_id ORDER BY call_start_dt DESC)=1
)
WITH DATA PRIMARY INDEX (accs_meth_id)


---utm table

DROP TABLE dp_tmp_rep.aak_slo_utm;
CREATE TABLE dp_tmp_rep.aak_slo_utm
AS
(
SEL
call_svc_type_cd
,'identifier of highest value' AS col1 --
,'identifier of highest value' AS col2 --
,'identifier of highest value' AS col3 --
,'identifier of highest value' AS col4 --
,'identifier of highest value' AS col5 --
,'identifier of highest value' AS col6 --
,'identifier of highest value' AS col7 --
,'identifier of highest value' AS col8 --
,'identifier of highest value' AS col9 --
,'identifier of highest value' AS col10 --
,'identifier of highest value' AS col11 --
,'identifier of highest value' AS col12 --
,'identifier of highest value' AS col13 --

FROM call_service_type
GROUP BY 1,2
) WITH DATA
PRIMARY INDEX(call_svc_type_cd); 

UPDATE  dp_tmp_rep.aak_slo_utm 
SET col1 = 'onnet' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('AT_1_CALL_OUT_LOCAL_ON',	'AT_1_CALL_OUT_LOCAL_ON_33',	'AT_1_CALL_OUT_LOCAL_ON_68',	'AT_1_FREE_INTERVAL_ON',	'AT_1_LBC128_FREE_INTERVAL_ON',	'AT_1_LBC15_FREE_INTERVAL_ON',	'AT_1_LBC16_FREE_INTERVAL_ON',	'AT_1_LBC22_FREE_INTERVAL_ON',	'AT_1_LBC31_FREE_INTERVAL_ON',	'AT_1_LBC32_FREE_INTERVAL_ON',	'AT_1_LBC40_FREE_INTERVAL_ON',	'AT_1_LBC41_FREE_INTERVAL_ON',	'AT_2_CALL_OUT_LOCAL_ON',	'AT_2_CALL_OUT_LOCAL_ON_33',	'AT_2_CALL_OUT_LOCAL_ON_68',	'AT_2_FREE_INTERVAL_ON',	'AT_2_LBC128_FREE_INTERVAL_ON',	'AT_2_LBC15_FREE_INTERVAL_ON',	'AT_2_LBC16_FREE_INTERVAL_ON',	'AT_2_LBC22_FREE_INTERVAL_ON',	'AT_2_LBC31_FREE_INTERVAL_ON',	'AT_2_LBC32_FREE_INTERVAL_ON',	'AT_2_LBC40_FREE_INTERVAL_ON',	'AT_2_LBC41_FREE_INTERVAL_ON',	'AT_3_CALL_OUT_LOCAL_ON',	'AT_3_CALL_OUT_LOCAL_ON_33',	'AT_3_CALL_OUT_LOCAL_ON_68',	'AT_3_FREE_INTERVAL_ON',	'AT_3_LBC128_FREE_INTERVAL_ON',	'AT_3_LBC15_FREE_INTERVAL_ON',	'AT_3_LBC16_FREE_INTERVAL_ON',	'AT_3_LBC22_FREE_INTERVAL_ON',	'AT_3_LBC31_FREE_INTERVAL_ON',	'AT_3_LBC32_FREE_INTERVAL_ON',	'AT_3_LBC40_FREE_INTERVAL_ON',	'AT_3_LBC41_FREE_INTERVAL_ON',	'AT_4_CALL_OUT_LOCAL_ON',	'AT_4_CALL_OUT_LOCAL_ON_33',	'AT_4_CALL_OUT_LOCAL_ON_68',	'AT_4_FREE_INTERVAL_ON',	'AT_4_LBC128_FREE_INTERVAL_ON',	'AT_4_LBC15_FREE_INTERVAL_ON',	'AT_4_LBC16_FREE_INTERVAL_ON',	'AT_4_LBC22_FREE_INTERVAL_ON',	'AT_4_LBC31_FREE_INTERVAL_ON',	'AT_4_LBC32_FREE_INTERVAL_ON',	'AT_4_LBC40_FREE_INTERVAL_ON',	'AT_4_LBC41_FREE_INTERVAL_ON',	'AT_5_CALL_OUT_LOCAL_ON',	'AT_5_CALL_OUT_LOCAL_ON_33',	'AT_5_CALL_OUT_LOCAL_ON_68',	'AT_5_FREE_INTERVAL_ON',	'AT_5_LBC128_FREE_INTERVAL_ON',	'AT_5_LBC15_FREE_INTERVAL_ON',	'AT_5_LBC16_FREE_INTERVAL_ON',	'AT_5_LBC22_FREE_INTERVAL_ON',	'AT_5_LBC31_FREE_INTERVAL_ON',	'AT_5_LBC32_FREE_INTERVAL_ON',	'AT_5_LBC40_FREE_INTERVAL_ON',	'AT_5_LBC41_FREE_INTERVAL_ON',	'AT_6_CALL_OUT_LOCAL_ON',	'AT_6_CALL_OUT_LOCAL_ON_33',	'AT_6_CALL_OUT_LOCAL_ON_68',	'AT_6_FREE_INTERVAL_ON',	'AT_6_LBC128_FREE_INTERVAL_ON',	'AT_6_LBC15_FREE_INTERVAL_ON',	'AT_6_LBC16_FREE_INTERVAL_ON',	'AT_6_LBC22_FREE_INTERVAL_ON',	'AT_6_LBC31_FREE_INTERVAL_ON',	'AT_6_LBC32_FREE_INTERVAL_ON',	'AT_6_LBC40_FREE_INTERVAL_ON',	'AT_6_LBC41_FREE_INTERVAL_ON',	'AT_7_CALL_OUT_LOCAL_ON',	'AT_7_CALL_OUT_LOCAL_ON_33',	'AT_7_CALL_OUT_LOCAL_ON_68',	'AT_7_FREE_INTERVAL_ON',	'AT_7_LBC128_FREE_INTERVAL_ON',	'AT_7_LBC15_FREE_INTERVAL_ON',	'AT_7_LBC16_FREE_INTERVAL_ON',	'AT_7_LBC22_FREE_INTERVAL_ON',	'AT_7_LBC31_FREE_INTERVAL_ON',	'AT_7_LBC32_FREE_INTERVAL_ON',	'AT_7_LBC40_FREE_INTERVAL_ON',	'AT_7_LBC41_FREE_INTERVAL_ON',	'AT_MUL_CALL_OUT_LOCAL_ON',	'AT_MUL_CALL_OUT_LOCAL_ON_33',	'AT_MUL_CALL_OUT_LOCAL_ON_68',	'AT_MUL_FREE_INTERVAL_ON',	'BCB_VOICE_ON',	'CALL_OUT_LOCAL_ON',	'CALL_OUT_LOCAL_ON_33',	'CALL_OUT_LOCAL_ON_68',	'FLAT_NIGHT',	'FLAT_NIGHT_ON',	'FREE_INTERVAL_ON',	'LBC128_FREE_INTERVAL_ON',	'LBC15_FREE_INTERVAL_ON',	'LBC16_FREE_INTERVAL_ON',	'LBC22_FREE_INTERVAL_ON',	'LBC31_FREE_INTERVAL_ON',	'LBC32_FREE_INTERVAL_ON',	'LBC40_FREE_INTERVAL_ON',	'LBC41_FREE_INTERVAL_ON',	'MUL_FEATURE_ON',	'OFF_PEAK_BONUS_ON') GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col2 = 'offnet' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('AT_1_CALL_OUT_LOCAL_OFF',	'AT_1_CALL_OUT_OMOB_OFF',	'AT_2_CALL_OUT_LOCAL_OFF',	'AT_2_CALL_OUT_OMOB_OFF',	'AT_3_CALL_OUT_LOCAL_OFF',	'AT_3_CALL_OUT_OMOB_OFF',	'AT_4_CALL_OUT_LOCAL_OFF',	'AT_4_CALL_OUT_OMOB_OFF',	'AT_5_CALL_OUT_LOCAL_OFF',	'AT_5_CALL_OUT_OMOB_OFF',	'AT_6_CALL_OUT_LOCAL_OFF',	'AT_6_CALL_OUT_OMOB_OFF',	'AT_7_CALL_OUT_LOCAL_OFF',	'AT_7_CALL_OUT_OMOB_OFF',	'AT_MUL_CALL_OUT_LOCAL_OFF',	'AT_MUL_CALL_OUT_OMOB_OFF',	'CALL_OUT_LOCAL_OFF',	'CALL_OUT_OMOB_OFF',	'FREE_INTERVAL_OFF',	'LBC128_FREE_INTERVAL_OFF',	'LBC22_FREE_INTERVAL_OFF',	'LBC31_FREE_INTERVAL_OFF',	'OFF_PEAK_BONUS_OFF') GROUP BY 1)
; 

UPDATE dp_tmp_rep.aak_slo_utm
SET col3 = 'fnf' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('AT_1_FNF_OUT_OFF_1',	'AT_1_FNF_OUT_OFF_2',	'AT_1_FNF_OUT_OFF_3',	'AT_1_FNF_OUT_ON_1',	'AT_1_FNF_OUT_ON_2',	'AT_1_FNF_OUT_ON_3',	'AT_1_FNF_OUT_ON_33_1',	'AT_1_FNF_OUT_ON_33_2',	'AT_1_FNF_OUT_ON_33_3',	'AT_1_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_1_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_1_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_1_LBC128_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_1_LBC128_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_1_LBC128_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_1_LBC15_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_1_LBC15_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_1_LBC15_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_1_LBC16_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_1_LBC16_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_1_LBC16_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_1_LBC22_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_1_LBC22_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_1_LBC22_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_1_LBC31_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_1_LBC31_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_1_LBC31_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_1_LBC32_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_1_LBC32_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_1_LBC32_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_1_LBC41_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_1_LBC41_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_2_FNF_INT_15',	'AT_2_FNF_OUT_OFF_1',	'AT_2_FNF_OUT_OFF_11',	'AT_2_FNF_OUT_OFF_12',	'AT_2_FNF_OUT_OFF_2',	'AT_2_FNF_OUT_OFF_3',	'AT_2_FNF_OUT_OFF_4',	'AT_2_FNF_OUT_OFF_5',	'AT_2_FNF_OUT_OFF_6',	'AT_2_FNF_OUT_OFF_9',	'AT_2_FNF_OUT_ON_1',	'AT_2_FNF_OUT_ON_10',	'AT_2_FNF_OUT_ON_11',	'AT_2_FNF_OUT_ON_12',	'AT_2_FNF_OUT_ON_13',	'AT_2_FNF_OUT_ON_14',	'AT_2_FNF_OUT_ON_15',	'AT_2_FNF_OUT_ON_16',	'AT_2_FNF_OUT_ON_17',	'AT_2_FNF_OUT_ON_2',	'AT_2_FNF_OUT_ON_3',	'AT_2_FNF_OUT_ON_33',	'AT_2_FNF_OUT_ON_33_1',	'AT_2_FNF_OUT_ON_33_10',	'AT_2_FNF_OUT_ON_33_11',	'AT_2_FNF_OUT_ON_33_12',	'AT_2_FNF_OUT_ON_33_13',	'AT_2_FNF_OUT_ON_33_15',	'AT_2_FNF_OUT_ON_33_16',	'AT_2_FNF_OUT_ON_33_17',	'AT_2_FNF_OUT_ON_33_2',	'AT_2_FNF_OUT_ON_33_3',	'AT_2_FNF_OUT_ON_33_4',	'AT_2_FNF_OUT_ON_33_5',	'AT_2_FNF_OUT_ON_33_6',	'AT_2_FNF_OUT_ON_33_7',	'AT_2_FNF_OUT_ON_33_8',	'AT_2_FNF_OUT_ON_33_9',	'AT_2_FNF_OUT_ON_4',	'AT_2_FNF_OUT_ON_5',	'AT_2_FNF_OUT_ON_6',	'AT_2_FNF_OUT_ON_7',	'AT_2_FNF_OUT_ON_8',	'AT_2_FNF_OUT_ON_9',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_2_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_2_LBC128_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_LBC128_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_2_LBC128_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_2_LBC128_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_2_LBC128_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_2_LBC15_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_LBC15_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_2_LBC15_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_2_LBC15_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_2_LBC16_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_2_LBC22_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_LBC22_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_2_LBC22_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_2_LBC22_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_2_LBC31_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_2_LBC32_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_2_LBC40_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_2_LBC41_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_3_FNF_OUT_OFF_1',	'AT_3_FNF_OUT_OFF_10',	'AT_3_FNF_OUT_OFF_11',	'AT_3_FNF_OUT_OFF_12',	'AT_3_FNF_OUT_OFF_13',	'AT_3_FNF_OUT_OFF_14',	'AT_3_FNF_OUT_OFF_15',	'AT_3_FNF_OUT_OFF_16',	'AT_3_FNF_OUT_OFF_17',	'AT_3_FNF_OUT_OFF_2',	'AT_3_FNF_OUT_OFF_3',	'AT_3_FNF_OUT_OFF_4',	'AT_3_FNF_OUT_OFF_5',	'AT_3_FNF_OUT_OFF_6',	'AT_3_FNF_OUT_OFF_7',	'AT_3_FNF_OUT_OFF_8',	'AT_3_FNF_OUT_OFF_9',	'AT_3_FNF_OUT_ON_1',	'AT_3_FNF_OUT_ON_10',	'AT_3_FNF_OUT_ON_11',	'AT_3_FNF_OUT_ON_12',	'AT_3_FNF_OUT_ON_13',	'AT_3_FNF_OUT_ON_14',	'AT_3_FNF_OUT_ON_15',	'AT_3_FNF_OUT_ON_16',	'AT_3_FNF_OUT_ON_17',	'AT_3_FNF_OUT_ON_2',	'AT_3_FNF_OUT_ON_3',	'AT_3_FNF_OUT_ON_33',	'AT_3_FNF_OUT_ON_33_1',	'AT_3_FNF_OUT_ON_33_10',	'AT_3_FNF_OUT_ON_33_11',	'AT_3_FNF_OUT_ON_33_12',	'AT_3_FNF_OUT_ON_33_13',	'AT_3_FNF_OUT_ON_33_14',	'AT_3_FNF_OUT_ON_33_15',	'AT_3_FNF_OUT_ON_33_16',	'AT_3_FNF_OUT_ON_33_17',	'AT_3_FNF_OUT_ON_33_2',	'AT_3_FNF_OUT_ON_33_3',	'AT_3_FNF_OUT_ON_33_4',	'AT_3_FNF_OUT_ON_33_5',	'AT_3_FNF_OUT_ON_33_6',	'AT_3_FNF_OUT_ON_33_7',	'AT_3_FNF_OUT_ON_33_8',	'AT_3_FNF_OUT_ON_33_9',	'AT_3_FNF_OUT_ON_4',	'AT_3_FNF_OUT_ON_5',	'AT_3_FNF_OUT_ON_6',	'AT_3_FNF_OUT_ON_7',	'AT_3_FNF_OUT_ON_8',	'AT_3_FNF_OUT_ON_9',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_3_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_3_LBC128_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_3_LBC15_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_3_LBC16_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_3_LBC22_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_3_LBC31_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_3_LBC32_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_3_LBC40_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_3_LBC41_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_4_FNF_INT_12',	'AT_4_FNF_OUT_OFF_1',	'AT_4_FNF_OUT_OFF_10',	'AT_4_FNF_OUT_OFF_11',	'AT_4_FNF_OUT_OFF_13',	'AT_4_FNF_OUT_OFF_14',	'AT_4_FNF_OUT_OFF_15',	'AT_4_FNF_OUT_OFF_16',	'AT_4_FNF_OUT_OFF_2',	'AT_4_FNF_OUT_OFF_3',	'AT_4_FNF_OUT_OFF_4',	'AT_4_FNF_OUT_OFF_5',	'AT_4_FNF_OUT_OFF_6',	'AT_4_FNF_OUT_OFF_7',	'AT_4_FNF_OUT_OFF_8',	'AT_4_FNF_OUT_OFF_9',	'AT_4_FNF_OUT_ON_1',	'AT_4_FNF_OUT_ON_10',	'AT_4_FNF_OUT_ON_11',	'AT_4_FNF_OUT_ON_12',	'AT_4_FNF_OUT_ON_13',	'AT_4_FNF_OUT_ON_14',	'AT_4_FNF_OUT_ON_15',	'AT_4_FNF_OUT_ON_16',	'AT_4_FNF_OUT_ON_17',	'AT_4_FNF_OUT_ON_2',	'AT_4_FNF_OUT_ON_3',	'AT_4_FNF_OUT_ON_33_1',	'AT_4_FNF_OUT_ON_33_10',	'AT_4_FNF_OUT_ON_33_11',	'AT_4_FNF_OUT_ON_33_12',	'AT_4_FNF_OUT_ON_33_13',	'AT_4_FNF_OUT_ON_33_14',	'AT_4_FNF_OUT_ON_33_15',	'AT_4_FNF_OUT_ON_33_16',	'AT_4_FNF_OUT_ON_33_17',	'AT_4_FNF_OUT_ON_33_2',	'AT_4_FNF_OUT_ON_33_3',	'AT_4_FNF_OUT_ON_33_4',	'AT_4_FNF_OUT_ON_33_5',	'AT_4_FNF_OUT_ON_33_6',	'AT_4_FNF_OUT_ON_33_7',	'AT_4_FNF_OUT_ON_33_8',	'AT_4_FNF_OUT_ON_33_9',	'AT_4_FNF_OUT_ON_4',	'AT_4_FNF_OUT_ON_5',	'AT_4_FNF_OUT_ON_6',	'AT_4_FNF_OUT_ON_7',	'AT_4_FNF_OUT_ON_8',	'AT_4_FNF_OUT_ON_9',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_LBC128_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_LBC15_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_LBC16_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_LBC22_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_LBC31_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_LBC32_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_LBC40_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_4_LBC41_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_5_FNF_OUT_OFF_1',	'AT_5_FNF_OUT_OFF_10',	'AT_5_FNF_OUT_OFF_11',	'AT_5_FNF_OUT_OFF_12',	'AT_5_FNF_OUT_OFF_13',	'AT_5_FNF_OUT_OFF_14',	'AT_5_FNF_OUT_OFF_15',	'AT_5_FNF_OUT_OFF_16',	'AT_5_FNF_OUT_OFF_17',	'AT_5_FNF_OUT_OFF_2',	'AT_5_FNF_OUT_OFF_3',	'AT_5_FNF_OUT_OFF_4',	'AT_5_FNF_OUT_OFF_5',	'AT_5_FNF_OUT_OFF_6',	'AT_5_FNF_OUT_OFF_7',	'AT_5_FNF_OUT_OFF_8',	'AT_5_FNF_OUT_OFF_9',	'AT_5_FNF_OUT_ON_1',	'AT_5_FNF_OUT_ON_10',	'AT_5_FNF_OUT_ON_11',	'AT_5_FNF_OUT_ON_12',	'AT_5_FNF_OUT_ON_13',	'AT_5_FNF_OUT_ON_14',	'AT_5_FNF_OUT_ON_15',	'AT_5_FNF_OUT_ON_16',	'AT_5_FNF_OUT_ON_17',	'AT_5_FNF_OUT_ON_2',	'AT_5_FNF_OUT_ON_3',	'AT_5_FNF_OUT_ON_33_1',	'AT_5_FNF_OUT_ON_33_10',	'AT_5_FNF_OUT_ON_33_11',	'AT_5_FNF_OUT_ON_33_12',	'AT_5_FNF_OUT_ON_33_13',	'AT_5_FNF_OUT_ON_33_14',	'AT_5_FNF_OUT_ON_33_15',	'AT_5_FNF_OUT_ON_33_16',	'AT_5_FNF_OUT_ON_33_17',	'AT_5_FNF_OUT_ON_33_2',	'AT_5_FNF_OUT_ON_33_3',	'AT_5_FNF_OUT_ON_33_4',	'AT_5_FNF_OUT_ON_33_5',	'AT_5_FNF_OUT_ON_33_6',	'AT_5_FNF_OUT_ON_33_7',	'AT_5_FNF_OUT_ON_33_8',	'AT_5_FNF_OUT_ON_33_9',	'AT_5_FNF_OUT_ON_4',	'AT_5_FNF_OUT_ON_5',	'AT_5_FNF_OUT_ON_6',	'AT_5_FNF_OUT_ON_7',	'AT_5_FNF_OUT_ON_8',	'AT_5_FNF_OUT_ON_9',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_5_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_5_LBC128_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_5_LBC128_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_5_LBC128_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_5_LBC15_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_5_LBC15_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_5_LBC16_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_5_LBC16_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_5_LBC22_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_5_LBC22_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_5_LBC22_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_5_LBC31_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_5_LBC31_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_5_LBC31_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_5_LBC32_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_5_LBC32_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_5_LBC40_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_5_LBC40_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_5_LBC40_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_5_LBC40_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_5_LBC40_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_5_LBC41_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_5_LBC41_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_FNF_OUT_OFF_1',	'AT_6_FNF_OUT_OFF_2',	'AT_6_FNF_OUT_OFF_3',	'AT_6_FNF_OUT_OFF_5',	'AT_6_FNF_OUT_ON_1',	'AT_6_FNF_OUT_ON_10',	'AT_6_FNF_OUT_ON_11',	'AT_6_FNF_OUT_ON_14',	'AT_6_FNF_OUT_ON_15',	'AT_6_FNF_OUT_ON_2',	'AT_6_FNF_OUT_ON_3',	'AT_6_FNF_OUT_ON_33',	'AT_6_FNF_OUT_ON_33_1',	'AT_6_FNF_OUT_ON_33_10',	'AT_6_FNF_OUT_ON_33_11',	'AT_6_FNF_OUT_ON_33_2',	'AT_6_FNF_OUT_ON_33_3',	'AT_6_FNF_OUT_ON_33_4',	'AT_6_FNF_OUT_ON_33_5',	'AT_6_FNF_OUT_ON_33_6',	'AT_6_FNF_OUT_ON_33_7',	'AT_6_FNF_OUT_ON_33_8',	'AT_6_FNF_OUT_ON_33_9',	'AT_6_FNF_OUT_ON_4',	'AT_6_FNF_OUT_ON_5',	'AT_6_FNF_OUT_ON_6',	'AT_6_FNF_OUT_ON_7',	'AT_6_FNF_OUT_ON_8',	'AT_6_FNF_OUT_ON_9',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_6_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_6_LBC128_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_6_LBC128_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_6_LBC128_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_LBC15_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_6_LBC15_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_6_LBC15_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_LBC16_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_6_LBC16_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_6_LBC16_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_LBC22_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_6_LBC22_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_6_LBC22_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_LBC22_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_6_LBC31_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_6_LBC31_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_6_LBC31_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_LBC31_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_6_LBC32_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_6_LBC32_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_6_LBC32_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_6_LBC40_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_6_LBC41_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_6_LBC41_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_FNF_OUT_OFF_1',	'AT_7_FNF_OUT_OFF_10',	'AT_7_FNF_OUT_OFF_11',	'AT_7_FNF_OUT_OFF_12',	'AT_7_FNF_OUT_OFF_13',	'AT_7_FNF_OUT_OFF_14',	'AT_7_FNF_OUT_OFF_15',	'AT_7_FNF_OUT_OFF_16',	'AT_7_FNF_OUT_OFF_17',	'AT_7_FNF_OUT_OFF_2',	'AT_7_FNF_OUT_OFF_3',	'AT_7_FNF_OUT_OFF_4',	'AT_7_FNF_OUT_OFF_5',	'AT_7_FNF_OUT_OFF_6',	'AT_7_FNF_OUT_OFF_7',	'AT_7_FNF_OUT_OFF_8',	'AT_7_FNF_OUT_OFF_9',	'AT_7_FNF_OUT_ON_1',	'AT_7_FNF_OUT_ON_10',	'AT_7_FNF_OUT_ON_11',	'AT_7_FNF_OUT_ON_12',	'AT_7_FNF_OUT_ON_13',	'AT_7_FNF_OUT_ON_14',	'AT_7_FNF_OUT_ON_15',	'AT_7_FNF_OUT_ON_16',	'AT_7_FNF_OUT_ON_17',	'AT_7_FNF_OUT_ON_2',	'AT_7_FNF_OUT_ON_3',	'AT_7_FNF_OUT_ON_33',	'AT_7_FNF_OUT_ON_33_1',	'AT_7_FNF_OUT_ON_33_10',	'AT_7_FNF_OUT_ON_33_11',	'AT_7_FNF_OUT_ON_33_12',	'AT_7_FNF_OUT_ON_33_13',	'AT_7_FNF_OUT_ON_33_14',	'AT_7_FNF_OUT_ON_33_15',	'AT_7_FNF_OUT_ON_33_16',	'AT_7_FNF_OUT_ON_33_17',	'AT_7_FNF_OUT_ON_33_2',	'AT_7_FNF_OUT_ON_33_3',	'AT_7_FNF_OUT_ON_33_4',	'AT_7_FNF_OUT_ON_33_5',	'AT_7_FNF_OUT_ON_33_6',	'AT_7_FNF_OUT_ON_33_7',	'AT_7_FNF_OUT_ON_33_8',	'AT_7_FNF_OUT_ON_33_9',	'AT_7_FNF_OUT_ON_4',	'AT_7_FNF_OUT_ON_5',	'AT_7_FNF_OUT_ON_6',	'AT_7_FNF_OUT_ON_7',	'AT_7_FNF_OUT_ON_8',	'AT_7_FNF_OUT_ON_9',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_17',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_7_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_7_LBC128_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_7_LBC128_FREE_INTERVAL_OFF',	'AT_7_LBC15_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_LBC15_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_7_LBC15_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_7_LBC15_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_LBC15_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_7_LBC15_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_7_LBC15_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_7_LBC15_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_7_LBC16_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_7_LBC22_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_3 ',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_7_LBC31_FREE_INTERVAL_FNF_OUT_ON_8 ',	'AT_7_LBC32_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_LBC32_FREE_INTERVAL_FNF_OUT_ON_13',	'AT_7_LBC32_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_LBC32_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_7_LBC32_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_7_LBC32_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_16',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_7_LBC40_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_1',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_10',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_11',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_12',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_14',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_15',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_2',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_3',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_4',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_5',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_6',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_7',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_8',	'AT_7_LBC41_FREE_INTERVAL_FNF_OUT_ON_9',	'AT_MUL_FNF_OUT_ON_1',	'AT_MUL_FNF_OUT_ON_2',	'AT_MUL_FNF_OUT_ON_3',	'AT_MUL_FNF_OUT_ON_33_1',	'AT_MUL_FNF_OUT_ON_33_2',	'AT_MUL_FNF_OUT_ON_33_3',	'FNF_ON_FLAT_NIGHT_ON',	'FNF_OUT_OFF',	'FNF_OUT_OFF_1',	'FNF_OUT_OFF_10',	'FNF_OUT_OFF_11',	'FNF_OUT_OFF_12',	'FNF_OUT_OFF_13',	'FNF_OUT_OFF_14',	'FNF_OUT_OFF_15',	'FNF_OUT_OFF_16',	'FNF_OUT_OFF_17',	'FNF_OUT_OFF_18',	'FNF_OUT_OFF_2',	'FNF_OUT_OFF_3',	'FNF_OUT_OFF_4',	'FNF_OUT_OFF_5',	'FNF_OUT_OFF_6',	'FNF_OUT_OFF_7',	'FNF_OUT_OFF_8',	'FNF_OUT_OFF_9',	'FNF_OUT_ON',	'FNF_OUT_ON_1',	'FNF_OUT_ON_10',	'FNF_OUT_ON_11',	'FNF_OUT_ON_12',	'FNF_OUT_ON_13',	'FNF_OUT_ON_14',	'FNF_OUT_ON_15',	'FNF_OUT_ON_16',	'FNF_OUT_ON_17',	'FNF_OUT_ON_18',	'FNF_OUT_ON_2',	'FNF_OUT_ON_3',	'FNF_OUT_ON_33',	'FNF_OUT_ON_33_1',	'FNF_OUT_ON_33_10',	'FNF_OUT_ON_33_11',	'FNF_OUT_ON_33_12',	'FNF_OUT_ON_33_13',	'FNF_OUT_ON_33_14',	'FNF_OUT_ON_33_15',	'FNF_OUT_ON_33_16',	'FNF_OUT_ON_33_17',	'FNF_OUT_ON_33_18 ',	'FNF_OUT_ON_33_2',	'FNF_OUT_ON_33_3',	'FNF_OUT_ON_33_4',	'FNF_OUT_ON_33_5',	'FNF_OUT_ON_33_6',	'FNF_OUT_ON_33_7',	'FNF_OUT_ON_33_8',	'FNF_OUT_ON_33_9',	'FNF_OUT_ON_4',	'FNF_OUT_ON_5',	'FNF_OUT_ON_6',	'FNF_OUT_ON_68',	'FNF_OUT_ON_68_1',	'FNF_OUT_ON_68_10',	'FNF_OUT_ON_68_11',	'FNF_OUT_ON_68_12',	'FNF_OUT_ON_68_13',	'FNF_OUT_ON_68_14',	'FNF_OUT_ON_68_15',	'FNF_OUT_ON_68_16',	'FNF_OUT_ON_68_17',	'FNF_OUT_ON_68_18',	'FNF_OUT_ON_68_2',	'FNF_OUT_ON_68_3',	'FNF_OUT_ON_68_4',	'FNF_OUT_ON_68_5',	'FNF_OUT_ON_68_6',	'FNF_OUT_ON_68_7',	'FNF_OUT_ON_68_8',	'FNF_OUT_ON_68_9',	'FNF_OUT_ON_7',	'FNF_OUT_ON_8',	'FNF_OUT_ON_9',	'FREE_INTERVAL_FNF_OUT_ON_1',	'FREE_INTERVAL_FNF_OUT_ON_10',	'FREE_INTERVAL_FNF_OUT_ON_11',	'FREE_INTERVAL_FNF_OUT_ON_12',	'FREE_INTERVAL_FNF_OUT_ON_13',	'FREE_INTERVAL_FNF_OUT_ON_14',	'FREE_INTERVAL_FNF_OUT_ON_15',	'FREE_INTERVAL_FNF_OUT_ON_16',	'FREE_INTERVAL_FNF_OUT_ON_17',	'FREE_INTERVAL_FNF_OUT_ON_18 ',	'FREE_INTERVAL_FNF_OUT_ON_2',	'FREE_INTERVAL_FNF_OUT_ON_3',	'FREE_INTERVAL_FNF_OUT_ON_4',	'FREE_INTERVAL_FNF_OUT_ON_5',	'FREE_INTERVAL_FNF_OUT_ON_6',	'FREE_INTERVAL_FNF_OUT_ON_7',	'FREE_INTERVAL_FNF_OUT_ON_8',	'FREE_INTERVAL_FNF_OUT_ON_9',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_1',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_10',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_11',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_12',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_13',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_14',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_15',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_16',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_17',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_18',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_2',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_3',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_4',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_5',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_6',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_7',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_8',	'LBC128_FREE_INTERVAL_FNF_OUT_ON_9',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_1',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_10',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_11',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_12',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_13',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_14',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_15',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_16',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_17',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_2',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_3',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_4',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_5',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_6',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_7',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_8',	'LBC15_FREE_INTERVAL_FNF_OUT_ON_9',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_1',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_10',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_11',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_12',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_13',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_14',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_15',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_16',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_17',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_18 ',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_2',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_3',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_4',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_5',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_6',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_7',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_8',	'LBC16_FREE_INTERVAL_FNF_OUT_ON_9',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_1',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_10',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_11',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_12',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_13',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_14',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_15',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_16',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_17',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_2',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_3',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_4',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_5',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_6',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_7',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_8',	'LBC22_FREE_INTERVAL_FNF_OUT_ON_9',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_1',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_10',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_11',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_12',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_13',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_14',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_15',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_16',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_17',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_18 ',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_2',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_3',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_4',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_5',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_6',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_7',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_8',	'LBC31_FREE_INTERVAL_FNF_OUT_ON_9',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_1',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_10',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_11',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_12',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_13',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_14',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_15',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_16',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_17',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_2',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_3',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_4',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_5',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_6',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_7',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_8',	'LBC32_FREE_INTERVAL_FNF_OUT_ON_9',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_1',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_10',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_11',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_12',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_13',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_14',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_15',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_16',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_17',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_2',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_3',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_4',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_5',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_6',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_7',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_8',	'LBC40_FREE_INTERVAL_FNF_OUT_ON_9',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_1',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_10',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_11',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_12',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_13',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_14',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_15',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_16',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_17',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_18',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_2',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_3',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_4',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_5',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_6',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_7',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_8',	'LBC41_FREE_INTERVAL_FNF_OUT_ON_9' ) GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col4 = 'IDD' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('AT_1_FNF_INT_1',	'AT_1_FNF_INT_2',	'AT_1_FNF_INT_3',	'AT_1_INT_CALL_G1',	'AT_1_INT_CALL_G1_G16_SC',	'AT_1_INT_CALL_G1_P1',	'AT_1_INT_CALL_G1_SC',	'AT_1_INT_CALL_G10',	'AT_1_INT_CALL_G11',	'AT_1_INT_CALL_G12',	'AT_1_INT_CALL_G15_SC_P3',	'AT_1_INT_CALL_G2',	'AT_1_INT_CALL_G3',	'AT_1_INT_CALL_G3_SC',	'AT_1_INT_CALL_G4',	'AT_1_INT_CALL_G4_G16_SC',	'AT_1_INT_CALL_G4_SC',	'AT_1_INT_CALL_G6',	'AT_1_INT_CALL_G6_P2',	'AT_1_INT_CALL_G7',	'AT_1_INT_CALL_G8',	'AT_1_INT_CALL_G9',	'AT_2_FNF_INT_1',	'AT_2_FNF_INT_2',	'AT_2_FNF_INT_3',	'AT_2_FNF_INT_8',	'AT_2_INT_CALL_G1',	'AT_2_INT_CALL_G1_SC',	'AT_2_INT_CALL_G10',	'AT_2_INT_CALL_G11',	'AT_2_INT_CALL_G15_SC_P3',	'AT_2_INT_CALL_G2',	'AT_2_INT_CALL_G3',	'AT_2_INT_CALL_G3_SC',	'AT_2_INT_CALL_G4',	'AT_2_INT_CALL_G4_G16_SC',	'AT_2_INT_CALL_G6',	'AT_2_INT_CALL_G6_P2',	'AT_2_INT_CALL_G7',	'AT_2_INT_CALL_G8',	'AT_2_INT_CALL_G9',	'AT_3_FNF_INT_1',	'AT_3_FNF_INT_10',	'AT_3_FNF_INT_11',	'AT_3_FNF_INT_12',	'AT_3_FNF_INT_13',	'AT_3_FNF_INT_14',	'AT_3_FNF_INT_15',	'AT_3_FNF_INT_16',	'AT_3_FNF_INT_2',	'AT_3_FNF_INT_3',	'AT_3_FNF_INT_4',	'AT_3_FNF_INT_5',	'AT_3_FNF_INT_6',	'AT_3_FNF_INT_7',	'AT_3_FNF_INT_8',	'AT_3_FNF_INT_9',	'AT_3_INT_CALL_G1',	'AT_3_INT_CALL_G1_G16_SC',	'AT_3_INT_CALL_G1_P1',	'AT_3_INT_CALL_G1_SC',	'AT_3_INT_CALL_G10',	'AT_3_INT_CALL_G11',	'AT_3_INT_CALL_G15_SC_P3',	'AT_3_INT_CALL_G2',	'AT_3_INT_CALL_G3',	'AT_3_INT_CALL_G3_SC',	'AT_3_INT_CALL_G4',	'AT_3_INT_CALL_G4_G16_SC',	'AT_3_INT_CALL_G4_SC',	'AT_3_INT_CALL_G6',	'AT_3_INT_CALL_G6_P2',	'AT_3_INT_CALL_G7',	'AT_3_INT_CALL_G8',	'AT_3_INT_CALL_G9',	'AT_4_INT_CALL_G1',	'AT_4_INT_CALL_G1_P1',	'AT_4_INT_CALL_G1_SC',	'AT_4_INT_CALL_G11',	'AT_4_INT_CALL_G15_SC_P3',	'AT_4_INT_CALL_G2',	'AT_4_INT_CALL_G3',	'AT_4_INT_CALL_G3_SC',	'AT_4_INT_CALL_G4',	'AT_4_INT_CALL_G4_G16_SC',	'AT_4_INT_CALL_G6',	'AT_4_INT_CALL_G6_P2',	'AT_4_INT_CALL_G7',	'AT_4_INT_CALL_G8',	'AT_4_INT_CALL_G9',	'AT_5_FNF_INT_1',	'AT_5_FNF_INT_10',	'AT_5_FNF_INT_11',	'AT_5_FNF_INT_12',	'AT_5_FNF_INT_13',	'AT_5_FNF_INT_14',	'AT_5_FNF_INT_15',	'AT_5_FNF_INT_16',	'AT_5_FNF_INT_2',	'AT_5_FNF_INT_3',	'AT_5_FNF_INT_4',	'AT_5_FNF_INT_5',	'AT_5_FNF_INT_6',	'AT_5_FNF_INT_7',	'AT_5_FNF_INT_8',	'AT_5_FNF_INT_9',	'AT_5_INT_CALL_G1',	'AT_5_INT_CALL_G1_G16_SC',	'AT_5_INT_CALL_G1_SC',	'AT_5_INT_CALL_G10',	'AT_5_INT_CALL_G11',	'AT_5_INT_CALL_G12',	'AT_5_INT_CALL_G15_SC_P3',	'AT_5_INT_CALL_G2',	'AT_5_INT_CALL_G3',	'AT_5_INT_CALL_G3_SC',	'AT_5_INT_CALL_G4',	'AT_5_INT_CALL_G4_G16_SC',	'AT_5_INT_CALL_G4_SC',	'AT_5_INT_CALL_G6',	'AT_5_INT_CALL_G6_P2',	'AT_5_INT_CALL_G7',	'AT_5_INT_CALL_G8',	'AT_5_INT_CALL_G9',	'AT_6_FNF_INT_1',	'AT_6_FNF_INT_2',	'AT_6_FNF_INT_3',	'AT_6_INT_CALL_G1',	'AT_6_INT_CALL_G1_G16_SC',	'AT_6_INT_CALL_G1_P1',	'AT_6_INT_CALL_G1_SC',	'AT_6_INT_CALL_G10',	'AT_6_INT_CALL_G11',	'AT_6_INT_CALL_G12',	'AT_6_INT_CALL_G15_SC_P3',	'AT_6_INT_CALL_G2',	'AT_6_INT_CALL_G3',	'AT_6_INT_CALL_G3_SC',	'AT_6_INT_CALL_G4',	'AT_6_INT_CALL_G4_G16_SC',	'AT_6_INT_CALL_G6',	'AT_6_INT_CALL_G6_P2',	'AT_6_INT_CALL_G7',	'AT_6_INT_CALL_G8',	'AT_6_INT_CALL_G9',	'AT_7_FNF_INT_1',	'AT_7_FNF_INT_10',	'AT_7_FNF_INT_11',	'AT_7_FNF_INT_12',	'AT_7_FNF_INT_13',	'AT_7_FNF_INT_14',	'AT_7_FNF_INT_15',	'AT_7_FNF_INT_17',	'AT_7_FNF_INT_2',	'AT_7_FNF_INT_3',	'AT_7_FNF_INT_4',	'AT_7_FNF_INT_5',	'AT_7_FNF_INT_6',	'AT_7_FNF_INT_7',	'AT_7_FNF_INT_8',	'AT_7_FNF_INT_9',	'AT_7_INT_CALL_G1',	'AT_7_INT_CALL_G1_G16_SC',	'AT_7_INT_CALL_G1_P1',	'AT_7_INT_CALL_G1_SC',	'AT_7_INT_CALL_G10',	'AT_7_INT_CALL_G11',	'AT_7_INT_CALL_G12',	'AT_7_INT_CALL_G15_SC_P3',	'AT_7_INT_CALL_G2',	'AT_7_INT_CALL_G3',	'AT_7_INT_CALL_G3_SC',	'AT_7_INT_CALL_G4',	'AT_7_INT_CALL_G4_G16_SC',	'AT_7_INT_CALL_G4_SC',	'AT_7_INT_CALL_G6',	'AT_7_INT_CALL_G6_P2',	'AT_7_INT_CALL_G7',	'AT_7_INT_CALL_G8',	'AT_7_INT_CALL_G9',	'AT_MUL_INT_CALL_G1_SC',	'AT_MUL_INT_CALL_G4',	'BCB_VOICE_INT',	'FLAT_NIGHT_INT',	'FNF_INT',	'FNF_INT_1',	'FNF_INT_10',	'FNF_INT_11',	'FNF_INT_12',	'FNF_INT_13',	'FNF_INT_14',	'FNF_INT_15',	'FNF_INT_16',	'FNF_INT_17',	'FNF_INT_18 ',	'FNF_INT_2',	'FNF_INT_3',	'FNF_INT_4',	'FNF_INT_5',	'FNF_INT_6',	'FNF_INT_7',	'FNF_INT_8',	'FNF_INT_9',	'FNF_INT_FLAT_NIGHT_INT',	'FNF_OUT_INT ',	'INT_111_KSA_OFFER',	'INT_111_UAE_OFFER',	'INT_999_UK_OFFER',	'INT_999_US_CAN_OFFER',	'INT_CALL_G1',	'INT_CALL_G1_G16_SC',	'INT_CALL_G1_P1',	'INT_CALL_G1_SC',	'INT_CALL_G10',	'INT_CALL_G11',	'INT_CALL_G12',	'INT_CALL_G13',	'INT_CALL_G14',	'INT_CALL_G15_SC_P3',	'INT_CALL_G2',	'INT_CALL_G3',	'INT_CALL_G3_SC',	'INT_CALL_G4',	'INT_CALL_G4_G16_SC',	'INT_CALL_G4_SC',	'INT_CALL_G5',	'INT_CALL_G6',	'INT_CALL_G6_P2',	'INT_CALL_G7',	'INT_CALL_G7_P2',	'INT_CALL_G7_P3',	'INT_CALL_G8',	'INT_CALL_G9',	'INT_CALL_G9_P2' ) GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col5 = 'onnet_bundle' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('BCB_BUY_MORE_VOICE_ON',	'BUY_MORE_VOICE_ON' ) GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col6 = 'offnet_bundle' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('BCB_BUY_MORE_VOICE_OFF',	'BUY_MORE_VOICE_OFF' ) GROUP BY 1)
;


UPDATE dp_tmp_rep.aak_slo_utm
SET col7 = 'fnf_bundle' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name in ('AT_1_FNF_ON_BUY_MORE_VOICE_ON',	'AT_2_FNF_ON_BUY_MORE_VOICE_ON',	'AT_3_FNF_ON_BUY_MORE_VOICE_ON',	'AT_4_FNF_ON_BUY_MORE_VOICE_ON',	'AT_5_FNF_ON_BUY_MORE_VOICE_ON',	'AT_6_FNF_OFF_BUY_MORE_VOICE_OFF',	'AT_6_FNF_ON_BUY_MORE_VOICE_ON',	'AT_7_FNF_ON_BUY_MORE_VOICE_ON',	'FNF_OFF_BUY_MORE_VOICE_OFF',	'FNF_ON_BUY_MORE_VOICE_ON') GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col8 = 'idd_bundle' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ( 'AT_1_FNF_INT_BUY_MORE_VOICE_INT',	'AT_2_FNF_INT_BUY_MORE_VOICE_INT',	'AT_5_FNF_INT_BUY_MORE_VOICE_INT',	'AT_6_FNF_INT_BUY_MORE_VOICE_INT',	'AT_7_FNF_INT_BUY_MORE_VOICE_INT',	'BUY_MORE_VOICE_INT',	'FNF_INT_BUY_MORE_VOICE_INT'  ) GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col9 = 'onnet_sms' WHERE call_svc_type_cd IN (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('BCB_SMS_ON',	'SMS_OUT_ON'  ) GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col10 = 'offnet_sms' WHERE call_svc_type_cd IN  (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('BCB_SMS_OFF',	'FNF_SMS_OFF',	'FNF_SMS_OFF_1',	'FNF_SMS_OFF_2',	'FNF_SMS_OFF_3',	'FNF_SMS_OFF_4',	'FNF_SMS_OFF_5',	'FNF_SMS_OFF_6',	'FNF_SMS_ON',	'FNF_SMS_ON_1',	'FNF_SMS_ON_2',	'FNF_SMS_ON_3',	'FNF_SMS_ON_4',	'FNF_SMS_ON_5',	'FNF_SMS_ON_6',	'SMS_OUT_OFF',	'SMS_OUT_OFF'  ) GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col11 = 'IDD_sms' WHERE call_svc_type_cd IN  (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('BCB_SMS_INT',	'FNF_SMS_INT_G1',	'FNF_SMS_INT_G1_1',	'FNF_SMS_INT_G1_2',	'FNF_SMS_INT_G1_3',	'FNF_SMS_INT_G1_4',	'FNF_SMS_INT_G1_5',	'FNF_SMS_INT_G1_6',	'FNF_SMS_INT_G1_G16',	'FNF_SMS_INT_G1_G16_1',	'FNF_SMS_INT_G1_G16_2',	'FNF_SMS_INT_G16',	'FNF_SMS_INT_G16_1',	'FNF_SMS_INT_G16_2',	'FNF_SMS_INT_G16_3',	'FNF_SMS_INT_G16_4',	'FNF_SMS_INT_G16_5',	'FNF_SMS_INT_G16_6',	'FNF_SMS_INT_G3',	'FNF_SMS_INT_G4',	'FNF_SMS_INT_G4_1',	'FNF_SMS_INT_G4_2',	'FNF_SMS_INT_G4_3',	'FNF_SMS_INT_G4_5',	'FNF_SMS_INT_G4_6',	'FNF_SMS_INT_G5',	'FNF_SMS_INT_G5_2',	'FNF_SMS_INT_G5_3',	'FNF_SMS_INT_G5_4',	'FNF_SMS_INT_G5_5',	'FNF_SMS_INT_G5_6',	'FNF_SMS_INT_G6',	'FNF_SMS_INT_G6_1',	'FNF_SMS_INT_G6_2',	'FNF_SMS_INT_G6_3',	'FNF_SMS_INT_G6_4',	'FNF_SMS_INT_G6_5',	'FNF_SMS_INT_G6_6',	'FNF_SMS_INT_G8',	'FNF_SMS_INT_G8_1',	'FNF_SMS_INT_G8_2',	'FNF_SMS_INT_G8_3',	'FNF_SMS_INT_G8_4',	'FNF_SMS_INT_G8_5',	'FNF_SMS_INT_G8_6',	'SMS_INT_G1',	'SMS_INT_G1_G16',	'SMS_INT_G1_G16',	'SMS_INT_G10',	'SMS_INT_G11',	'SMS_INT_G12',	'SMS_INT_G13',	'SMS_INT_G14',	'SMS_INT_G15',	'SMS_INT_G16',	'SMS_INT_G2',	'SMS_INT_G3',	'SMS_INT_G3_G4',	'SMS_INT_G4',	'SMS_INT_G5',	'SMS_INT_G6',	'SMS_INT_G7',	'SMS_INT_G8',	'SMS_INT_G9' ) GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col12 = 'bundle_sms' WHERE call_svc_type_cd IN  (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('BUY_MORE_SMS_INT',	'BUY_MORE_SMS_OFF',	'BUY_MORE_SMS_ON' ) GROUP BY 1)
;

UPDATE dp_tmp_rep.aak_slo_utm
SET col13 = 'GPRS' WHERE call_svc_type_cd IN  (SEL call_svc_type_Cd FROM call_service_type WHERE call_svc_type_name IN ('AT_2_ALFALAH_APN',	'AT_2_APN_CCBPL',	'AT_2_APN_NADRATRACKER',	'AT_2_APN_SSA',	'AT_2_APN_USAGE',	'AT_2_BUY_CROSS_BUNDLE_ALFALAH_APN',	'AT_2_BUY_CROSS_BUNDLE_APN_CCBPL',	'AT_2_BUY_CROSS_BUNDLE_APN_NADRATRACKER',	'AT_2_BUY_CROSS_BUNDLE_APN_SSA',	'AT_2_BUY_CROSS_BUNDLE_APN_USAGE',	'AT_2_BUY_CROSS_BUNDLE_CORP_GPRS',	'AT_2_BUY_CROSS_BUNDLE_DEFAULT_APN',	'AT_2_BUY_CROSS_BUNDLE_EPMARS_APN',	'AT_2_BUY_CROSS_BUNDLE_FWO_APN',	'AT_2_BUY_CROSS_BUNDLE_GPRS_BLACKBERRY',	'AT_2_BUY_CROSS_BUNDLE_GPRS_TEST_TPT1',	'AT_2_BUY_CROSS_BUNDLE_GPRS_TEST_TPT2',	'AT_2_BUY_CROSS_BUNDLE_GPRS_TRACKER',	'AT_2_BUY_CROSS_BUNDLE_INTERNET_GPRS',	'AT_2_BUY_CROSS_BUNDLE_INTERNET_TIME',	'AT_2_BUY_CROSS_BUNDLE_INTRANET_GPRS',	'AT_2_BUY_CROSS_BUNDLE_MAGIC_GPRS',	'AT_2_BUY_CROSS_BUNDLE_MEMAIL',	'AT_2_BUY_CROSS_BUNDLE_MMS_GPRS',	'AT_2_BUY_CROSS_BUNDLE_MMS_MOBILINK',	'AT_2_BUY_CROSS_BUNDLE_MMS_UFONE',	'AT_2_BUY_CROSS_BUNDLE_MMS_WARID',	'AT_2_BUY_CROSS_BUNDLE_MMS_ZONG',	'AT_2_BUY_CROSS_BUNDLE_PSO_GPRS',	'AT_2_BUY_CROSS_BUNDLE_R_INTERNET_GPRS',	'AT_2_BUY_CROSS_BUNDLE_R_MMS_GPRS',	'AT_2_BUY_CROSS_BUNDLE_R_WAP_GPRS',	'AT_2_BUY_CROSS_BUNDLE_RED_TIME60',	'AT_2_BUY_CROSS_BUNDLE_TAMEER_BANK',	'AT_2_BUY_CROSS_BUNDLE_TV_GPRS',	'AT_2_BUY_CROSS_BUNDLE_USBdata_BAL_Check',	'AT_2_BUY_CROSS_BUNDLE_WAP_GPRS',	'AT_2_BUY_CROSS_BUNDLE_ZERO_GPRS',	'AT_2_BUY_MORE_ALFALAH_APN',	'AT_2_BUY_MORE_APN_CCBPL',	'AT_2_BUY_MORE_APN_NADRATRACKER',	'AT_2_BUY_MORE_APN_SSA',	'AT_2_BUY_MORE_APN_USAGE',	'AT_2_BUY_MORE_CORP_GPRS',	'AT_2_BUY_MORE_DEFAULT_APN',	'AT_2_BUY_MORE_EPMARS_APN',	'AT_2_BUY_MORE_FWO_APN',	'AT_2_BUY_MORE_GPRS_BLACKBERRY',	'AT_2_BUY_MORE_GPRS_TEST_TPT1',	'AT_2_BUY_MORE_GPRS_TEST_TPT2',	'AT_2_BUY_MORE_GPRS_TRACKER',	'AT_2_BUY_MORE_INTERNET_GPRS',	'AT_2_BUY_MORE_INTERNET_TIME',	'AT_2_BUY_MORE_INTRANET_GPRS',	'AT_2_BUY_MORE_MAGIC_GPRS',	'AT_2_BUY_MORE_MEMAIL',	'AT_2_BUY_MORE_MMS_GPRS',	'AT_2_BUY_MORE_MMS_MOBILINK',	'AT_2_BUY_MORE_MMS_UFONE',	'AT_2_BUY_MORE_MMS_WARID',	'AT_2_BUY_MORE_MMS_ZONG',	'AT_2_BUY_MORE_PSO_GPRS',	'AT_2_BUY_MORE_R_INTERNET_GPRS',	'AT_2_BUY_MORE_R_MMS_GPRS',	'AT_2_BUY_MORE_R_WAP_GPRS',	'AT_2_BUY_MORE_RED_TIME60',	'AT_2_BUY_MORE_TAMEER_BANK',	'AT_2_BUY_MORE_TV_GPRS',	'AT_2_BUY_MORE_USBdata_BAL_Check',	'AT_2_BUY_MORE_WAP_GPRS',	'AT_2_BUY_MORE_ZERO_GPRS',	'AT_2_CORP_GPRS',	'AT_2_DEFAULT_APN',	'AT_2_EPMARS_APN',	'AT_2_FWO_APN',	'AT_2_GPRS_BLACKBERRY',	'AT_2_GPRS_TEST_TPT1',	'AT_2_GPRS_TEST_TPT2',	'AT_2_GPRS_TRACKER',	'AT_2_INTERNET_GPRS',	'AT_2_INTERNET_TIME',	'AT_2_INTRANET_GPRS',	'AT_2_MAGIC_GPRS',	'AT_2_MEMAIL',	'AT_2_MMS_GPRS',	'AT_2_MMS_MOBILINK',	'AT_2_MMS_UFONE',	'AT_2_MMS_WARID',	'AT_2_MMS_ZONG',	'AT_2_PSO_GPRS',	'AT_2_R_INTERNET_GPRS',	'AT_2_R_MMS_GPRS',	'AT_2_R_WAP_GPRS',	'AT_2_RED_TIME60',	'AT_2_TAMEER_BANK',	'AT_2_TV_GPRS',	'AT_2_USBdata_BAL_Check',	'AT_2_WAP_GPRS',	'AT_2_ZERO_GPRS',	'AT_6_ALFALAH_APN',	'AT_6_APN_CCBPL',	'AT_6_APN_NADRATRACKER',	'AT_6_APN_SSA',	'AT_6_APN_USAGE',	'AT_6_CORP_GPRS',	'AT_6_DEFAULT_APN',	'AT_6_EPMARS_APN',	'AT_6_FWO_APN',	'AT_6_GPRS_BLACKBERRY',	'AT_6_GPRS_TEST_TPT1',	'AT_6_GPRS_TEST_TPT2',	'AT_6_GPRS_TRACKER',	'AT_6_INTERNET_GPRS',	'AT_6_INTERNET_TIME',	'AT_6_INTRANET_GPRS',	'AT_6_MAGIC_GPRS',	'AT_6_MEMAIL',	'AT_6_MMS_GPRS',	'AT_6_MMS_MOBILINK',	'AT_6_MMS_UFONE',	'AT_6_MMS_WARID',	'AT_6_MMS_ZONG',	'AT_6_PSO_GPRS',	'AT_6_R_INTERNET_GPRS',	'AT_6_R_MMS_GPRS',	'AT_6_R_WAP_GPRS',	'AT_6_RED_TIME60',	'AT_6_TAMEER_BANK',	'AT_6_TV_GPRS',	'AT_6_USBdata_BAL_Check',	'AT_6_WAP_GPRS',	'AT_6_ZERO_GPRS',	'BMM_ALFALAH_APN',	'BMM_APN_CCBPL',	'BMM_APN_NADRATRACKER',	'BMM_APN_SSA',	'BMM_APN_USAGE',	'BMM_BUY_CROSS_BUNDLE_ALFALAH_APN',	'BMM_BUY_CROSS_BUNDLE_APN_CCBPL',	'BMM_BUY_CROSS_BUNDLE_APN_NADRATRACKER',	'BMM_BUY_CROSS_BUNDLE_APN_SSA',	'BMM_BUY_CROSS_BUNDLE_APN_USAGE',	'BMM_BUY_CROSS_BUNDLE_CORP_GPRS',	'BMM_BUY_CROSS_BUNDLE_DEFAULT_APN',	'BMM_BUY_CROSS_BUNDLE_EPMARS_APN',	'BMM_BUY_CROSS_BUNDLE_FWO_APN',	'BMM_BUY_CROSS_BUNDLE_GPRS_BLACKBERRY',	'BMM_BUY_CROSS_BUNDLE_GPRS_TEST_TPT1',	'BMM_BUY_CROSS_BUNDLE_GPRS_TEST_TPT2',	'BMM_BUY_CROSS_BUNDLE_GPRS_TRACKER',	'BMM_BUY_CROSS_BUNDLE_INTERNET_GPRS',	'BMM_BUY_CROSS_BUNDLE_INTERNET_TIME',	'BMM_BUY_CROSS_BUNDLE_INTRANET_GPRS',	'BMM_BUY_CROSS_BUNDLE_MAGIC_GPRS',	'BMM_BUY_CROSS_BUNDLE_MEMAIL',	'BMM_BUY_CROSS_BUNDLE_MMS_GPRS',	'BMM_BUY_CROSS_BUNDLE_MMS_MOBILINK',	'BMM_BUY_CROSS_BUNDLE_MMS_UFONE',	'BMM_BUY_CROSS_BUNDLE_MMS_WARID',	'BMM_BUY_CROSS_BUNDLE_MMS_ZONG',	'BMM_BUY_CROSS_BUNDLE_PSO_GPRS',	'BMM_BUY_CROSS_BUNDLE_R_INTERNET_GPRS',	'BMM_BUY_CROSS_BUNDLE_R_MMS_GPRS',	'BMM_BUY_CROSS_BUNDLE_R_WAP_GPRS',	'BMM_BUY_CROSS_BUNDLE_RED_TIME60',	'BMM_BUY_CROSS_BUNDLE_TAMEER_BANK',	'BMM_BUY_CROSS_BUNDLE_time',	'BMM_BUY_CROSS_BUNDLE_time_apn',	'BMM_BUY_CROSS_BUNDLE_TV_GPRS',	'BMM_BUY_CROSS_BUNDLE_USBdata_BAL_Check',	'BMM_BUY_CROSS_BUNDLE_WAP_GPRS',	'BMM_BUY_CROSS_BUNDLE_ZERO_GPRS',	'BMM_BUY_MORE_ALFALAH_APN',	'BMM_BUY_MORE_APN_CCBPL',	'BMM_BUY_MORE_APN_NADRATRACKER',	'BMM_BUY_MORE_APN_SSA',	'BMM_BUY_MORE_APN_USAGE',	'BMM_BUY_MORE_CORP_GPRS',	'BMM_BUY_MORE_DEFAULT_APN',	'BMM_BUY_MORE_EPMARS_APN',	'BMM_BUY_MORE_FWO_APN',	'BMM_BUY_MORE_GPRS_BLACKBERRY',	'BMM_BUY_MORE_GPRS_TEST_TPT1',	'BMM_BUY_MORE_GPRS_TEST_TPT2',	'BMM_BUY_MORE_GPRS_TRACKER',	'BMM_BUY_MORE_INTERNET_GPRS',	'BMM_BUY_MORE_INTERNET_TIME',	'BMM_BUY_MORE_INTRANET_GPRS',	'BMM_BUY_MORE_MAGIC_GPRS',	'BMM_BUY_MORE_MEMAIL',	'BMM_BUY_MORE_MMS_GPRS',	'BMM_BUY_MORE_MMS_MOBILINK',	'BMM_BUY_MORE_MMS_UFONE',	'BMM_BUY_MORE_MMS_WARID',	'BMM_BUY_MORE_MMS_ZONG',	'BMM_BUY_MORE_PSO_GPRS',	'BMM_BUY_MORE_R_INTERNET_GPRS',	'BMM_BUY_MORE_R_MMS_GPRS',	'BMM_BUY_MORE_R_WAP_GPRS',	'BMM_BUY_MORE_RED_TIME60',	'BMM_BUY_MORE_TAMEER_BANK',	'BMM_BUY_MORE_time',	'BMM_BUY_MORE_time_apn',	'BMM_BUY_MORE_TV_GPRS',	'BMM_BUY_MORE_USBdata_BAL_Check',	'BMM_BUY_MORE_WAP_GPRS',	'BMM_BUY_MORE_ZERO_GPRS',	'BMM_CORP_GPRS',	'BMM_DEFAULT_APN',	'BMM_EPMARS_APN',	'BMM_FCA_VOL_ALFALAH_APN',	'BMM_FCA_VOL_APN_CCBPL',	'BMM_FCA_VOL_APN_NADRATRACKER',	'BMM_FCA_VOL_APN_SSA',	'BMM_FCA_VOL_APN_USAGE',	'BMM_FCA_VOL_CORP_GPRS',	'BMM_FCA_VOL_DEFAULT_APN',	'BMM_FCA_VOL_EPMARS_APN',	'BMM_FCA_VOL_FWO_APN',	'BMM_FCA_VOL_GPRS_BLACKBERRY',	'BMM_FCA_VOL_GPRS_TEST_TPT1',	'BMM_FCA_VOL_GPRS_TEST_TPT2',	'BMM_FCA_VOL_GPRS_TRACKER',	'BMM_FCA_VOL_INTERNET_GPRS',	'BMM_FCA_VOL_INTERNET_TIME',	'BMM_FCA_VOL_INTRANET_GPRS',	'BMM_FCA_VOL_MAGIC_GPRS',	'BMM_FCA_VOL_MEMAIL',	'BMM_FCA_VOL_MMS_GPRS',	'BMM_FCA_VOL_MMS_MOBILINK',	'BMM_FCA_VOL_MMS_UFONE',	'BMM_FCA_VOL_MMS_WARID',	'BMM_FCA_VOL_MMS_ZONG',	'BMM_FCA_VOL_PSO_GPRS',	'BMM_FCA_VOL_R_INTERNET_GPRS',	'BMM_FCA_VOL_R_MMS_GPRS',	'BMM_FCA_VOL_R_WAP_GPRS',	'BMM_FCA_VOL_RED_TIME60',	'BMM_FCA_VOL_TAMEER_BANK',	'BMM_FCA_VOL_TV_GPRS',	'BMM_FCA_VOL_USBdata_BAL_Check',	'BMM_FCA_VOL_WAP_GPRS',	'BMM_FCA_VOL_ZERO_GPRS',	'BMM_FWO_APN',	'BMM_GPRS_BLACKBERRY',	'BMM_GPRS_TEST_TPT1',	'BMM_GPRS_TEST_TPT2',	'BMM_GPRS_TRACKER',	'BMM_INTERNET_GPRS',	'BMM_INTERNET_TIME',	'BMM_INTRANET_GPRS',	'BMM_MAGIC_GPRS',	'BMM_MEMAIL',	'BMM_MMS_GPRS',	'BMM_MMS_MOBILINK',	'BMM_MMS_UFONE',	'BMM_MMS_WARID',	'BMM_MMS_ZONG',	'BMM_PSO_GPRS',	'BMM_R_INTERNET_GPRS',	'BMM_R_MMS_GPRS',	'BMM_R_WAP_GPRS',	'BMM_RED_TIME60',	'BMM_TAMEER_BANK',	'BMM_time',	'BMM_time_apn',	'BMM_TV_GPRS',	'BMM_USBdata_BAL_Check',	'BMM_WAP_GPRS',	'BMM_ZERO_GPRS',	'BUY_CROSS_BUNDLE_ALFALAH_APN',	'BUY_CROSS_BUNDLE_APN_CCBPL',	'BUY_CROSS_BUNDLE_APN_NADRATRACKER',	'BUY_CROSS_BUNDLE_APN_SSA',	'BUY_CROSS_BUNDLE_APN_USAGE',	'BUY_CROSS_BUNDLE_CORP_GPRS',	'BUY_CROSS_BUNDLE_DEFAULT_APN',	'BUY_CROSS_BUNDLE_EPMARS_APN',	'BUY_CROSS_BUNDLE_FWO_APN',	'BUY_CROSS_BUNDLE_GPRS_BLACKBERRY',	'BUY_CROSS_BUNDLE_GPRS_TEST_TPT1',	'BUY_CROSS_BUNDLE_GPRS_TEST_TPT2',	'BUY_CROSS_BUNDLE_GPRS_TRACKER',	'BUY_CROSS_BUNDLE_INTERNET_GPRS',	'BUY_CROSS_BUNDLE_INTERNET_TIME',	'BUY_CROSS_BUNDLE_INTRANET_GPRS',	'BUY_CROSS_BUNDLE_MAGIC_GPRS',	'BUY_CROSS_BUNDLE_MEMAIL',	'BUY_CROSS_BUNDLE_MMS_GPRS',	'BUY_CROSS_BUNDLE_MMS_MOBILINK',	'BUY_CROSS_BUNDLE_MMS_UFONE',	'BUY_CROSS_BUNDLE_MMS_WARID',	'BUY_CROSS_BUNDLE_MMS_ZONG',	'BUY_CROSS_BUNDLE_PSO_GPRS',	'BUY_CROSS_BUNDLE_R_INTERNET_GPRS',	'BUY_CROSS_BUNDLE_R_MMS_GPRS',	'BUY_CROSS_BUNDLE_R_WAP_GPRS',	'BUY_CROSS_BUNDLE_RED_TIME60',	'BUY_CROSS_BUNDLE_TAMEER_BANK',	'BUY_CROSS_BUNDLE_TV_GPRS',	'BUY_CROSS_BUNDLE_USBdata_BAL_Check',	'BUY_CROSS_BUNDLE_WAP_GPRS',	'BUY_CROSS_BUNDLE_ZERO_GPRS',	'BUY_MORE_ALFALAH_APN',	'BUY_MORE_APN_CCBPL',	'BUY_MORE_APN_NADRATRACKER',	'BUY_MORE_APN_SSA',	'BUY_MORE_APN_USAGE',	'BUY_MORE_CORP_GPRS',	'BUY_MORE_DEFAULT_APN',	'BUY_MORE_EPMARS_APN',	'BUY_MORE_FWO_APN',	'BUY_MORE_GPRS_BLACKBERRY',	'BUY_MORE_GPRS_TEST_TPT1',	'BUY_MORE_GPRS_TEST_TPT2',	'BUY_MORE_GPRS_TRACKER',	'BUY_MORE_INTERNET_GPRS',	'BUY_MORE_INTERNET_TIME',	'BUY_MORE_INTRANET_GPRS',	'BUY_MORE_MAGIC_GPRS',	'BUY_MORE_MEMAIL',	'BUY_MORE_MMS_GPRS',	'BUY_MORE_MMS_MOBILINK',	'BUY_MORE_MMS_UFONE',	'BUY_MORE_MMS_WARID',	'BUY_MORE_MMS_ZONG',	'BUY_MORE_PSO_GPRS',	'BUY_MORE_R_INTERNET_GPRS',	'BUY_MORE_R_MMS_GPRS',	'BUY_MORE_R_WAP_GPRS',	'BUY_MORE_RED_TIME60',	'BUY_MORE_TAMEER_BANK',	'BUY_MORE_TV_GPRS',	'BUY_MORE_USBdata_BAL_Check',	'BUY_MORE_WAP_GPRS',	'BUY_MORE_ZERO_GPRS',	'CORP_GPRS',	'DEFAULT_APN',	'FCA_VOL_ALFALAH_APN',	'FCA_VOL_APN_CCBPL',	'FCA_VOL_APN_NADRATRACKER',	'FCA_VOL_APN_SSA',	'FCA_VOL_APN_USAGE',	'FCA_VOL_CORP_GPRS',	'FCA_VOL_DEFAULT_APN',	'FCA_VOL_EPMARS_APN',	'FCA_VOL_FWO_APN',	'FCA_VOL_GPRS_BLACKBERRY',	'FCA_VOL_GPRS_TEST_TPT1',	'FCA_VOL_GPRS_TEST_TPT2',	'FCA_VOL_GPRS_TRACKER',	'FCA_VOL_INTERNET_GPRS',	'FCA_VOL_INTERNET_TIME',	'FCA_VOL_INTRANET_GPRS',	'FCA_VOL_MAGIC_GPRS',	'FCA_VOL_MEMAIL',	'FCA_VOL_MMS_GPRS',	'FCA_VOL_MMS_MOBILINK',	'FCA_VOL_MMS_UFONE',	'FCA_VOL_MMS_WARID',	'FCA_VOL_MMS_ZONG',	'FCA_VOL_PSO_GPRS',	'FCA_VOL_R_INTERNET_GPRS',	'FCA_VOL_R_MMS_GPRS',	'FCA_VOL_R_WAP_GPRS',	'FCA_VOL_RED_TIME60',	'FCA_VOL_TAMEER_BANK',	'FCA_VOL_TV_GPRS',	'FCA_VOL_USBdata_BAL_Check',	'FCA_VOL_WAP_GPRS',	'FCA_VOL_ZERO_GPRS',	'GBS_ALFALAH_APN',	'GBS_APN_CCBPL',	'GBS_APN_NADRATRACKER',	'GBS_APN_SSA',	'GBS_APN_USAGE',	'GBS_BUY_CROSS_BUNDLE_ALFALAH_APN',	'GBS_BUY_CROSS_BUNDLE_APN_CCBPL',	'GBS_BUY_CROSS_BUNDLE_APN_NADRATRACKER',	'GBS_BUY_CROSS_BUNDLE_APN_SSA',	'GBS_BUY_CROSS_BUNDLE_APN_USAGE',	'GBS_BUY_CROSS_BUNDLE_CORP_GPRS',	'GBS_BUY_CROSS_BUNDLE_DEFAULT_APN',	'GBS_BUY_CROSS_BUNDLE_EPMARS_APN',	'GBS_BUY_CROSS_BUNDLE_FWO_APN',	'GBS_BUY_CROSS_BUNDLE_GPRS_BLACKBERRY',	'GBS_BUY_CROSS_BUNDLE_GPRS_TEST_TPT1',	'GBS_BUY_CROSS_BUNDLE_GPRS_TEST_TPT2',	'GBS_BUY_CROSS_BUNDLE_GPRS_TRACKER',	'GBS_BUY_CROSS_BUNDLE_INTERNET_GPRS',	'GBS_BUY_CROSS_BUNDLE_INTERNET_TIME',	'GBS_BUY_CROSS_BUNDLE_INTRANET_GPRS',	'GBS_BUY_CROSS_BUNDLE_MAGIC_GPRS',	'GBS_BUY_CROSS_BUNDLE_MEMAIL',	'GBS_BUY_CROSS_BUNDLE_MMS_GPRS',	'GBS_BUY_CROSS_BUNDLE_MMS_MOBILINK',	'GBS_BUY_CROSS_BUNDLE_MMS_UFONE',	'GBS_BUY_CROSS_BUNDLE_MMS_WARID',	'GBS_BUY_CROSS_BUNDLE_MMS_ZONG',	'GBS_BUY_CROSS_BUNDLE_PSO_GPRS',	'GBS_BUY_CROSS_BUNDLE_R_INTERNET_GPRS',	'GBS_BUY_CROSS_BUNDLE_R_MMS_GPRS',	'GBS_BUY_CROSS_BUNDLE_R_WAP_GPRS',	'GBS_BUY_CROSS_BUNDLE_RED_TIME60',	'GBS_BUY_CROSS_BUNDLE_TAMEER_BANK',	'GBS_BUY_CROSS_BUNDLE_TV_GPRS',	'GBS_BUY_CROSS_BUNDLE_USBdata_BAL_Check',	'GBS_BUY_CROSS_BUNDLE_WAP_GPRS',	'GBS_BUY_CROSS_BUNDLE_ZERO_GPRS',	'GBS_BUY_MORE_ALFALAH_APN',	'GBS_BUY_MORE_APN_CCBPL',	'GBS_BUY_MORE_APN_NADRATRACKER',	'GBS_BUY_MORE_APN_SSA',	'GBS_BUY_MORE_APN_USAGE',	'GBS_BUY_MORE_CORP_GPRS',	'GBS_BUY_MORE_DEFAULT_APN',	'GBS_BUY_MORE_EPMARS_APN',	'GBS_BUY_MORE_FWO_APN',	'GBS_BUY_MORE_GPRS_BLACKBERRY',	'GBS_BUY_MORE_GPRS_TEST_TPT1',	'GBS_BUY_MORE_GPRS_TEST_TPT2',	'GBS_BUY_MORE_GPRS_TRACKER',	'GBS_BUY_MORE_INTERNET_GPRS',	'GBS_BUY_MORE_INTERNET_TIME',	'GBS_BUY_MORE_INTRANET_GPRS',	'GBS_BUY_MORE_MAGIC_GPRS',	'GBS_BUY_MORE_MEMAIL',	'GBS_BUY_MORE_MMS_GPRS',	'GBS_BUY_MORE_MMS_MOBILINK',	'GBS_BUY_MORE_MMS_UFONE',	'GBS_BUY_MORE_MMS_WARID',	'GBS_BUY_MORE_MMS_ZONG',	'GBS_BUY_MORE_PSO_GPRS',	'GBS_BUY_MORE_R_INTERNET_GPRS',	'GBS_BUY_MORE_R_MMS_GPRS',	'GBS_BUY_MORE_R_WAP_GPRS',	'GBS_BUY_MORE_RED_TIME60',	'GBS_BUY_MORE_TAMEER_BANK',	'GBS_BUY_MORE_TV_GPRS',	'GBS_BUY_MORE_USBdata_BAL_Check',	'GBS_BUY_MORE_WAP_GPRS',	'GBS_BUY_MORE_ZERO_GPRS',	'GBS_CORP_GPRS',	'GBS_DEFAULT_APN',	'GBS_EPMARS_APN',	'GBS_FCA_VOL_ALFALAH_APN',	'GBS_FCA_VOL_APN_CCBPL',	'GBS_FCA_VOL_APN_NADRATRACKER',	'GBS_FCA_VOL_APN_SSA',	'GBS_FCA_VOL_APN_USAGE',	'GBS_FCA_VOL_CORP_GPRS',	'GBS_FCA_VOL_DEFAULT_APN',	'GBS_FCA_VOL_EPMARS_APN',	'GBS_FCA_VOL_FWO_APN',	'GBS_FCA_VOL_GPRS_BLACKBERRY',	'GBS_FCA_VOL_GPRS_TEST_TPT1',	'GBS_FCA_VOL_GPRS_TEST_TPT2',	'GBS_FCA_VOL_GPRS_TRACKER',	'GBS_FCA_VOL_INTERNET_GPRS',	'GBS_FCA_VOL_INTERNET_TIME',	'GBS_FCA_VOL_INTRANET_GPRS',	'GBS_FCA_VOL_MAGIC_GPRS',	'GBS_FCA_VOL_MEMAIL',	'GBS_FCA_VOL_MMS_GPRS',	'GBS_FCA_VOL_MMS_MOBILINK',	'GBS_FCA_VOL_MMS_UFONE',	'GBS_FCA_VOL_MMS_WARID',	'GBS_FCA_VOL_MMS_ZONG',	'GBS_FCA_VOL_PSO_GPRS',	'GBS_FCA_VOL_R_INTERNET_GPRS',	'GBS_FCA_VOL_R_MMS_GPRS',	'GBS_FCA_VOL_R_WAP_GPRS',	'GBS_FCA_VOL_RED_TIME60',	'GBS_FCA_VOL_TAMEER_BANK',	'GBS_FCA_VOL_TV_GPRS',	'GBS_FCA_VOL_USBdata_BAL_Check',	'GBS_FCA_VOL_WAP_GPRS',	'GBS_FCA_VOL_ZERO_GPRS',	'GBS_FWO_APN',	'GBS_GPRS_BLACKBERRY',	'GBS_GPRS_TEST_TPT1',	'GBS_GPRS_TEST_TPT2',	'GBS_GPRS_TRACKER',	'GBS_INTERNET_GPRS',	'GBS_INTERNET_TIME',	'GBS_INTRANET_GPRS',	'GBS_MAGIC_GPRS',	'GBS_MEMAIL',	'GBS_MMS_GPRS',	'GBS_MMS_MOBILINK',	'GBS_MMS_UFONE',	'GBS_MMS_WARID',	'GBS_MMS_ZONG',	'GBS_PSO_GPRS',	'GBS_R_INTERNET_GPRS',	'GBS_R_MMS_GPRS',	'GBS_R_WAP_GPRS',	'GBS_RED_TIME60',	'GBS_TAMEER_BANK',	'GBS_TV_GPRS',	'GBS_USBdata_BAL_Check',	'GBS_WAP_GPRS',	'GBS_ZERO_GPRS',	'GPRS_TRACKER',	'INTERNET_GPRS',	'INTERNET_TIME',	'INTRANET_GPRS',	'MEMAIL',	'MMS_GPRS',	'PSO_GPRS',	'R_INTERNET_GPRS',	'R_MMS_GPRS',	'R_WAP_GPRS',	'RECUR_BUY_GPRS_ALFALAH_APN',	'RECUR_BUY_GPRS_APN_CCBPL',	'RECUR_BUY_GPRS_APN_NADRATRACKER',	'RECUR_BUY_GPRS_APN_SSA',	'RECUR_BUY_GPRS_APN_USAGE',	'RECUR_BUY_GPRS_CORP_GPRS',	'RECUR_BUY_GPRS_DEFAULT_APN',	'RECUR_BUY_GPRS_EPMARS_APN',	'RECUR_BUY_GPRS_FWO_APN',	'RECUR_BUY_GPRS_GPRS_BLACKBERRY',	'RECUR_BUY_GPRS_GPRS_TEST_TPT1',	'RECUR_BUY_GPRS_GPRS_TEST_TPT2',	'RECUR_BUY_GPRS_GPRS_TRACKER',	'RECUR_BUY_GPRS_INTERNET_GPRS',	'RECUR_BUY_GPRS_INTERNET_TIME',	'RECUR_BUY_GPRS_INTRANET_GPRS',	'RECUR_BUY_GPRS_MAGIC_GPRS',	'RECUR_BUY_GPRS_MEMAIL',	'RECUR_BUY_GPRS_MMS_GPRS',	'RECUR_BUY_GPRS_MMS_MOBILINK',	'RECUR_BUY_GPRS_MMS_UFONE',	'RECUR_BUY_GPRS_MMS_WARID',	'RECUR_BUY_GPRS_MMS_ZONG',	'RECUR_BUY_GPRS_PSO_GPRS',	'RECUR_BUY_GPRS_R_INTERNET_GPRS',	'RECUR_BUY_GPRS_R_MMS_GPRS',	'RECUR_BUY_GPRS_R_WAP_GPRS',	'RECUR_BUY_GPRS_RED_TIME60',	'RECUR_BUY_GPRS_TAMEER_BANK',	'RECUR_BUY_GPRS_TV_GPRS',	'RECUR_BUY_GPRS_USBdata_BAL_Check',	'RECUR_BUY_GPRS_WAP_GPRS',	'RECUR_BUY_GPRS_ZERO_GPRS',	'RED_TIME60',	'SMS_777',	'TV_GPRS',	'USBdata_BAL_Check',	'USsD_999',	'WAP_GPRS',	'APN_USAGE',	'TAMEER_BANK',	'GPRS_BLACKBERRY',	'GPRS_TEST_TPT2',	'GPRS_TEST_TPT1',	'MAGIC_GPRS',	'MMS_ZONG',	'MMS_UFONE',	'MMS_WARID',	'MMS_MOBILINK',	'ALFALAH_APN',	'FWO_APN',	'APN_SSA',	'ZERO_GPRS',	'EPMARS_APN',	'APN_NADRATRACKER',	'APN_CCBPL',	'AT_1_INTRANET_GPRS',	'AT_1_WAP_GPRS',	'AT_1_INTERNET_GPRS',	'AT_1_MMS_GPRS',	'AT_1_MEMAIL',	'AT_1_GPRS_TRACKER',	'AT_1_CORP_GPRS',	'AT_1_PSO_GPRS',	'AT_1_TV_GPRS',	'AT_1_TAMEER_BANK',	'AT_1_GPRS_BLACKBERRY',	'AT_1_GPRS_TEST_TPT2',	'AT_1_GPRS_TEST_TPT1',	'AT_1_INTERNET_TIME',	'AT_1_MAGIC_GPRS',	'AT_1_MMS_ZONG',	'AT_1_MMS_UFONE',	'AT_1_MMS_WARID',	'AT_1_MMS_MOBILINK',	'AT_1_DEFAULT_APN',	'AT_1_ALFALAH_APN',	'AT_1_FWO_APN',	'AT_1_ZERO_GPRS',	'AT_1_APN_SSA',	'AT_1_EPMARS_APN',	'AT_1_RED_TIME60' ) GROUP BY 1)
;



--Traffic Rev

sel offering_name from dp_tmp_rep.aak_slo_trf a left join DP_VEW.OFFR b on a.offering_id = b.Offering_Id group by 1
SEL max(Call_Start_Dt) FROM dp_tmp_rep.aak_slo_trf
CREATE   TABLE dp_tmp_rep.aak_slo_trf
AS
(
SEL
a.accs_meth_id
,file_dt
,call_start_dt
,offering_id
,COALESCE(SUM(call_gross_revenue_amt),0) Total_Traffic_Rev
,COALESCE(SUM(call_rated_vol),0) Total_Traffic_Mins

-- revenues
,SUM(CASE WHEN col1 = 'onnet' and Call_Gross_Revenue_Amt > 0 then  call_gross_revenue_amt ELSE 0 END) AS Charged_Onnet_Rev
,SUM(CASE WHEN col1 = 'onnet' and Call_Gross_Revenue_Amt = 0 then  call_gross_revenue_amt ELSE 0 END) AS UnCharged_Onnet_Rev
,SUM(CASE WHEN col2 = 'offnet'  THEN call_gross_revenue_amt ELSE 0 END) AS Regular_Offnet_Rev
,SUM(CASE WHEN col3 = 'fnf' THEN call_gross_revenue_amt ELSE 0 END) AS IDD_Rev
,SUM(CASE WHEN col4 = 'IDD'  and Call_Gross_Revenue_Amt > 0 then  call_gross_revenue_amt ELSE 0 END) AS Charged_FNF_Rev
,SUM(CASE WHEN col4 = 'IDD'  and Call_Gross_Revenue_Amt = 0 then  call_gross_revenue_amt ELSE 0 END) AS UnCharged_FNF_Rev

,SUM(CASE WHEN col5 = 'onnet_bundle' THEN call_gross_revenue_amt ELSE 0 END) AS onnet_bundle_Rev
,SUM(CASE WHEN  col6 = 'offnet_bundle' THEN call_gross_revenue_amt ELSE 0 END) AS offnet_bundle_Rev
,SUM(CASE WHEN  col7 = 'fnf_bundle' THEN call_gross_revenue_amt ELSE 0 END) AS fnf_bundle_Rev
,SUM(CASE WHEN  col8 = 'idd_bundle' THEN call_gross_revenue_amt ELSE 0 END) AS idd_bundle_Rev
,SUM(CASE WHEN  col9 = 'onnet_sms' THEN call_gross_revenue_amt ELSE 0 END) AS onnet_sms_Rev
,SUM(CASE WHEN  col10 = 'offnet_sms' THEN call_gross_revenue_amt ELSE 0 END) AS offnet_sms_Rev
,SUM(CASE WHEN  col11 = 'IDD_sms' THEN call_gross_revenue_amt ELSE 0 END) AS IDD_sms_Rev
,SUM(CASE WHEN  col12 = 'bundle_sms' THEN call_gross_revenue_amt ELSE 0 END) AS bundle_sms_Rev
,SUM(CASE WHEN col13= 'GPRS' then call_gross_revenue_amt else 0 end) GPRS_rev

--volume
,SUM(CASE WHEN col1 = 'onnet' and Call_Gross_Revenue_Amt < 0 then  call_rated_vol ELSE 0 END) AS Charged_Onnet_vol
,SUM(CASE WHEN col1 = 'onnet' and Call_Gross_Revenue_Amt = 0 then  call_rated_vol ELSE 0 END) AS UnCharged_Onnet_vol
,SUM(CASE WHEN col2 = 'offnet'  THEN call_rated_vol ELSE 0 END) AS Regular_Offnet_vol
,SUM(CASE WHEN col3 = 'fnf' THEN call_rated_vol ELSE 0 END) AS IDD_vol
,SUM(CASE WHEN col4 = 'IDD'  and call_rated_vol > 0 then  call_gross_revenue_amt ELSE 0 END) AS Charged_FNF_vol
,SUM(CASE WHEN col4 = 'IDD'  and call_rated_vol = 0 then  call_gross_revenue_amt ELSE 0 END) AS UnCharged_FNF_vol

,SUM(CASE WHEN col5 = 'onnet_bundle' THEN call_rated_vol ELSE 0 END) AS onnet_bundle_vol
,SUM(CASE WHEN  col6 = 'offnet_bundle' THEN call_rated_vol ELSE 0 END) AS offnet_bundle_vol
,SUM(CASE WHEN  col7 = 'fnf_bundle' THEN call_rated_vol ELSE 0 END) AS fnf_bundle_vol
,SUM(CASE WHEN  col8 = 'idd_bundle' THEN call_rated_vol ELSE 0 END) AS idd_bundle_vol
,SUM(CASE WHEN  col9 = 'onnet_sms' THEN call_rated_vol ELSE 0 END) AS onnet_sms_vol
,SUM(CASE WHEN  col10 = 'offnet_sms' THEN call_rated_vol ELSE 0 END) AS offnet_sms_vol
,SUM(CASE WHEN  col11 = 'IDD_sms' THEN call_rated_vol ELSE 0 END) AS IDD_sms_vol
,SUM(CASE WHEN  col12 = 'bundle_sms' THEN call_rated_vol ELSE 0 END) AS bundle_sms_vol
,SUM(CASE WHEN col13= 'GPRS' then call_network_vol else 0 end) GPRS_vol

-- number of calls
,SUM(CASE WHEN col1 = 'onnet' and Call_Gross_Revenue_Amt < 0 then  1 ELSE 0 END) AS Charged_Onnet_calls
,SUM(CASE WHEN col1 = 'onnet' and Call_Gross_Revenue_Amt = 0 then  1 ELSE 0 END) AS UnCharged_Onnet_calls
,SUM(CASE WHEN col2 = 'offnet'  THEN 1 ELSE 0 END) AS Regular_Offnet_calls
,SUM(CASE WHEN col3 = 'fnf' THEN 1 ELSE 0 END) AS IDD_calls
,SUM(CASE WHEN col4 = 'IDD'  and call_rated_vol > 0 then  1 ELSE 0 END) AS Charged_FNF_calls
,SUM(CASE WHEN col4 = 'IDD'  and call_rated_vol = 0 then  1 ELSE 0 END) AS UnCharged_FNF_calls

,SUM(CASE WHEN col5 = 'onnet_bundle' THEN 1 ELSE 0 END) AS onnet_bundle_calls
,SUM(CASE WHEN  col6 = 'offnet_bundle' THEN 1 ELSE 0 END) AS offnet_bundle_calls
,SUM(CASE WHEN  col7 = 'fnf_bundle' THEN 1 ELSE 0 END) AS fnf_bundle_calls
,SUM(CASE WHEN  col8 = 'idd_bundle' THEN 1 ELSE 0 END) AS idd_bundle_calls
,SUM(CASE WHEN  col9 = 'onnet_sms' THEN 1 ELSE 0 END) AS onnet_sms_calls
,SUM(CASE WHEN  col10 = 'offnet_sms' THEN 1 ELSE 0 END) AS offnet_sms_calls
,SUM(CASE WHEN  col11 = 'IDD_sms' THEN 1 ELSE 0 END) AS IDD_sms_calls
,SUM(CASE WHEN  col12 = 'bundle_sms' THEN 1 ELSE 0 END) AS bundle_sms_calls


FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN call_hist b
ON a.accs_meth_id = b.accs_meth_id
INNER JOIN dp_tmp_rep.aak_slo_utm c
ON b.call_svc_type_cd = c.call_svc_type_cd 

WHERE call_start_dt BETWEEN file_dt AND current_date - 1

GROUP BY 1,2,3,4
)
WITH DATA PRIMARY INDEX (accs_meth_id, call_start_dt)

--SIP

SEL SUM(Total_Subscription_Rev) FROM dp_tmp_rep.aak_slo_sip WHERE file_dt = '2013-06-04' AND call_start_dt =  '2013-06-04'
CREATE  TABLE dp_tmp_rep.aak_slo_sip
AS
(
SEL
v.accs_meth_id
,v.file_dt
,v.call_start_dt
,SUM(v.Total_Subscription_Rev)Total_Subscription_Rev
FROM
(
SEL
a.accs_meth_id
,file_dt
,created_date AS call_start_dt
,COALESCE(SUM(unit_cost),0) AS Total_Subscription_Rev
FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN sip_snapshot b
ON a.accs_meth_id = b.accs_meth_id
WHERE action = 'add' AND status = 'success'
AND created_date BETWEEN file_dt AND current_date -1
GROUP BY 1,2,3

UNION ALL

SEL
a.accs_meth_id
,file_dt
,CAST(Confrmtn_Event_Start_Dt AS DATE) AS call_start_dt
,COALESCE(SUM(amount),0) Total_Subscription_Rev
FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN mediated_confrmtn_event b
ON a.accs_meth_id = b.accs_meth_id
WHERE CAST(Confrmtn_Event_Start_Dt AS DATE) BETWEEN file_dt AND current_date -1
AND amount > 0 
GROUP BY 1,2,3
)v
GROUP BY 1,2,3

)WITH DATA PRIMARY INDEX (accs_meth_id)

--Recharges

SEL * FROM  dp_tmp_rep.aak_slo_rech
SEL * FROM offr
CREATE  TABLE dp_tmp_rep.aak_slo_rech
AS
(

                   SEL accs_meth_id, 
                   v.file_dt,
                   v.call_start_dt,
					SUM(CASE WHEN refill_type_cd IN (999,14,5,13,27,0,  1,       2,       3,       4,       6,     7,       8,       9,          10,     11,     12,15, 16,     17,     18,     19,     20,     21,     22,     23,     24,     25,     26) THEN amnt END) Rech_Amount,
                   SUM(count_of_recharge)Recharge_count,
                   COUNT(DISTINCT v.accs_meth_id) AS RechSubs
                                      
                    --sum(amnt) as amnt,
                    --count (distinct_recharge_subs)distinct_recharge_subs
                   
                   FROM
                                                          (
                                                          SELECT        
                                                          recp_accs_meth_id AS accs_meth_id, 
                                                          file_dt,
                                                         CAST(txn_dt AS DATE)call_start_dt ,
                                                          refill_type_cd,
                                                          SUM(txn_credit) amnt,
                                                          SUM( CASE WHEN txn_credit >0 THEN 1 ELSE 0 END) count_of_recharge
                                                          
                                                          FROM            
                                                         dp_tmp_rep.aak_slo_base a
                                                         LEFT JOIN  dp_vew.vouch_trans_vew b    --this table is only for electronic and non-electronic scratch cards , so no need to add check of refill type code
                                                          ON a.accs_meth_id = b.recp_accs_meth_id
                                                          WHERE         
                                                      	txn_dt  BETWEEN file_dt  AND current_date -1
                                                          
                                                     --     AND recp_accs_meth_id IN (SEL accs_meth_id FROM dp_tmp_rep.asp_tajirpre_base GROUP BY 1)
                                                          GROUP BY 1,2,3,4
                                                          
                                                          UNION                       
                                                          
                                                          SELECT 
                                                          src1.accs_meth_id AS accs_meth_id,
                                                          file_dt,
                                                         CAST(dt_used AS DATE)call_start_dt ,
                                                          999 AS refill_type_cd,
                                                          SUM(src1.voucher_credit_amt) AS amnt,
                                                          COUNT(DISTINCT CASE WHEN src1.voucher_credit_amt >0 THEN 1 ELSE 0 END) count_of_recharge
                                                          
                                                          FROM dp_tmp_rep.aak_slo_base a
                                                          LEFT JOIN dp_vew.pre_vouch src1 
                                                          ON a.accs_meth_id = src1.accs_meth_id
                                                          INNER JOIN dp_vew.pre_vouch_stat_hist src2
                                                          ON src1.voucher_serial_num= src2.voucher_serial_num
                                                          AND src1.dt_used = src2.voucher_stat_start_dt
                                                          WHERE src1.dt_used BETWEEN file_dt AND current_date - 1
                                                          AND src2.voucher_stat_type_cd=3 -- used state
                                            --              AND accs_meth_id IN (SEL accs_meth_id FROM dp_tmp_rep.asp_tajirpre_base GROUP BY 1)
                                                GROUP BY 1,2,3,4
                                                )v
                                      GROUP BY 1,2,3



)WITH DATA PRIMARY INDEX(accs_meth_id)

--Unioning
CREATE  TABLE dp_tmp_rep.aak_slo_un
AS
(
SEL
v.accs_meth_id
,v.file_dt
,v.call_start_dt
FROM
(
SEL
accs_meth_id
,file_dt
,call_start_dt
FROM dp_tmp_rep.aak_slo_trf
GROUP BY 1,2,3

UNION

SEL
accs_meth_id
,file_dt
,call_start_dt
FROM dp_tmp_rep.aak_slo_sip
GROUP BY 1,2,3

UNION


SEL
accs_meth_id
,file_dt
,call_start_dt
FROM dp_tmp_rep.aak_slo_rech
GROUP BY 1,2,3

)v

GROUP BY 1,2,3
)
WITH DATA PRIMARY INDEX (accs_meth_id)


--Final Revenue

SEL * FROM  dp_tmp_rep.aak_slo_fnl
WHERE call_start_dt IS NOT NULL and call_start_dt < '2013-06-21'
ORDER BY 1,2,3
CREATE   TABLE dp_tmp_rep.aak_slo_fnl
AS
(
SEL
CASE
WHEN b.offering_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Priceplan
,a.file_dt AS Locking_Date
,f.call_start_dt
,SUM(g.Total_Traffic_Rev)Total_Traffic_Rev
,COUNT(DISTINCT a.accs_meth_id)Total_Subs
,COUNT(DISTINCT CASE WHEN g.Total_Traffic_Rev>0 OR g.Total_Traffic_Mins > 0 THEN g.accs_meth_id END ) AS Active_Subs
,SUM(g.Total_Traffic_Mins) Total_Traffic_Mins

-- revenues
,SUM(Charged_Onnet_Rev)Charged_Onnet_Rev
,SUM(UnCharged_Onnet_Rev)UnCharged_Onnet_Rev
,SUM(Regular_Offnet_Rev)Regular_Offnet_Rev
,SUM(IDD_Rev)IDD_Rev
,SUM(Charged_FNF_Rev)Charged_FNF_Rev
,SUM(UnCharged_FNF_Rev)UnCharged_FNF_Rev

,SUM(onnet_bundle_Rev)onnet_bundle_Rev
,SUM(offnet_bundle_Rev)offnet_bundle_Rev
,SUM(fnf_bundle_Rev)fnf_bundle_Rev
,SUM(idd_bundle_Rev)idd_bundle_Rev
,SUM(onnet_sms_Rev)onnet_sms_Rev
,SUM(offnet_sms_Rev)offnet_sms_Rev
,SUM(IDD_sms_Rev)IDD_sms_Rev
,SUM(bundle_sms_Rev)bundle_sms_Rev
,SUM(GPRS_rev)GPRS_rev

--volume
,SUM(Charged_Onnet_vol)Charged_Onnet_vol
,SUM(UnCharged_Onnet_vol)UnCharged_Onnet_vol
,SUM(Regular_Offnet_vol)Regular_Offnet_vol
,SUM(IDD_vol)IDD_vol
,SUM(Charged_FNF_vol)Charged_FNF_vol
,SUM(UnCharged_FNF_vol)UnCharged_FNF_vol

,SUM(onnet_bundle_vol)onnet_bundle_vol
,SUM(offnet_bundle_vol)offnet_bundle_vol
,SUM(fnf_bundle_vol)fnf_bundle_vol
,SUM(idd_bundle_vol)idd_bundle_vol
,SUM(onnet_sms_vol)onnet_sms_vol
,SUM(offnet_sms_vol)offnet_sms_vol
,SUM(IDD_sms_vol)IDD_sms_vol
,SUM(bundle_sms_vol)bundle_sms_vol
,SUM(GPRS_vol)GPRS_vol

-- number of calls
,SUM(Charged_Onnet_calls)Charged_Onnet_calls
,SUM(UnCharged_Onnet_calls)UnCharged_Onnet_calls
,SUM(Regular_Offnet_calls)Regular_Offnet_calls
,SUM(IDD_calls)IDD_calls
,SUM(Charged_FNF_calls)Charged_FNF_calls
,SUM(UnCharged_FNF_calls)UnCharged_FNF_calls

,SUM(onnet_bundle_calls)onnet_bundle_calls
,SUM(offnet_bundle_calls)offnet_bundle_calls
,SUM(fnf_bundle_calls)fnf_bundle_calls
,SUM(idd_bundle_calls)idd_bundle_calls
,SUM(onnet_sms_calls)onnet_sms_calls
,SUM(offnet_sms_calls)offnet_sms_calls
,SUM(IDD_sms_calls)IDD_sms_calls
,SUM(bundle_sms_calls)bundle_sms_calls

,SUM(h.Total_Subscription_Rev)Total_Subscription_Rev
,SUM(i.Rech_Amount)Rech_Amount
,SUM(i.Recharge_count)Recharge_count
,SUM(i.RechSubs)RechSubs

FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN  dp_tmp_rep.aak_slo_pp b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.file_dt
LEFT JOIN dp_tmp_rep.aak_slo_un f
ON a.accs_meth_id = f.accs_meth_id
AND a.file_dt = f.file_dt
LEFT JOIN dp_tmp_rep.aak_slo_trf g
ON a.accs_meth_id = g.accs_meth_id
AND a.file_dt = g.file_dt
AND f.call_start_dt = g.call_start_dt
LEFT JOIN dp_tmp_rep.aak_slo_sip h
ON a.accs_meth_id = h.accs_meth_id
AND a.file_dt = h.file_dt
AND f.call_start_dt = h.call_start_dt
LEFT JOIN dp_tmp_rep.aak_slo_rech i
ON a.accs_meth_id = i.accs_meth_id
AND a.file_dt = i.file_dt
AND f.call_start_dt = i.call_start_dt

GROUP BY 1,2,3
)
WITH DATA PRIMARY INDEX (Priceplan)



sel * from dp_tmp_rep.aak_slo_final
drop table dp_tmp_rep.aak_slo_final;
CREATE   TABLE dp_tmp_rep.aak_slo_final
AS
(
SEL
CASE
WHEN b.offering_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Priceplan
,a.file_dt AS Locking_Date
,f.call_start_dt
,SUM(g.Total_Traffic_Rev)Total_Traffic_Rev
,COUNT(DISTINCT a.accs_meth_id)Total_Subs
,COUNT(DISTINCT CASE WHEN g.Total_Traffic_Rev>0 OR g.Total_Traffic_Mins > 0 THEN g.accs_meth_id END ) AS Active_Subs
-- these 4 things added in this table . compared to fnl wala table
,COUNT(distinct case when g.gprs_vol > 0 or g.gprs_rev >0 then g.accs_meth_id end) as gprs_subs
,COUNT(case when g.gprs_vol > 0 and g.gprs_rev = 0 then g.accs_meth_id end) as bundle_subs
,SUM(case when g.gprs_vol > 0 and g.gprs_rev = 0 then g.gprs_rev end) as bundle_rev
,SUM(case when g.gprs_vol > 0 and g.gprs_rev = 0 then g.gprs_vol end) as bundle_vol

,SUM(g.Total_Traffic_Mins) Total_Traffic_Mins

-- revenues
,SUM(Charged_Onnet_Rev)Charged_Onnet_Rev
,SUM(UnCharged_Onnet_Rev)UnCharged_Onnet_Rev
,SUM(Regular_Offnet_Rev)Regular_Offnet_Rev
,SUM(IDD_Rev)IDD_Rev
,SUM(Charged_FNF_Rev)Charged_FNF_Rev
,SUM(UnCharged_FNF_Rev)UnCharged_FNF_Rev

,SUM(onnet_bundle_Rev)onnet_bundle_Rev
,SUM(offnet_bundle_Rev)offnet_bundle_Rev
,SUM(fnf_bundle_Rev)fnf_bundle_Rev
,SUM(idd_bundle_Rev)idd_bundle_Rev
,SUM(onnet_sms_Rev)onnet_sms_Rev
,SUM(offnet_sms_Rev)offnet_sms_Rev
,SUM(IDD_sms_Rev)IDD_sms_Rev
,SUM(bundle_sms_Rev)bundle_sms_Rev
,SUM(GPRS_rev)GPRS_rev

--volume
,SUM(Charged_Onnet_vol)Charged_Onnet_vol
,SUM(UnCharged_Onnet_vol)UnCharged_Onnet_vol
,SUM(Regular_Offnet_vol)Regular_Offnet_vol
,SUM(IDD_vol)IDD_vol
,SUM(Charged_FNF_vol)Charged_FNF_vol
,SUM(UnCharged_FNF_vol)UnCharged_FNF_vol

,SUM(onnet_bundle_vol)onnet_bundle_vol
,SUM(offnet_bundle_vol)offnet_bundle_vol
,SUM(fnf_bundle_vol)fnf_bundle_vol
,SUM(idd_bundle_vol)idd_bundle_vol
,SUM(onnet_sms_vol)onnet_sms_vol
,SUM(offnet_sms_vol)offnet_sms_vol
,SUM(IDD_sms_vol)IDD_sms_vol
,SUM(bundle_sms_vol)bundle_sms_vol
,SUM(GPRS_vol)GPRS_vol

-- number of calls
,SUM(Charged_Onnet_calls)Charged_Onnet_calls
,SUM(UnCharged_Onnet_calls)UnCharged_Onnet_calls
,SUM(Regular_Offnet_calls)Regular_Offnet_calls
,SUM(IDD_calls)IDD_calls
,SUM(Charged_FNF_calls)Charged_FNF_calls
,SUM(UnCharged_FNF_calls)UnCharged_FNF_calls

,SUM(onnet_bundle_calls)onnet_bundle_calls
,SUM(offnet_bundle_calls)offnet_bundle_calls
,SUM(fnf_bundle_calls)fnf_bundle_calls
,SUM(idd_bundle_calls)idd_bundle_calls
,SUM(onnet_sms_calls)onnet_sms_calls
,SUM(offnet_sms_calls)offnet_sms_calls
,SUM(IDD_sms_calls)IDD_sms_calls
,SUM(bundle_sms_calls)bundle_sms_calls

,SUM(h.Total_Subscription_Rev)Total_Subscription_Rev
,SUM(i.Rech_Amount)Rech_Amount
,SUM(i.Recharge_count)Recharge_count
,SUM(i.RechSubs)RechSubs

FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN  dp_tmp_rep.aak_slo_pp b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.file_dt
LEFT JOIN dp_tmp_rep.aak_slo_un f
ON a.accs_meth_id = f.accs_meth_id
AND a.file_dt = f.file_dt
LEFT JOIN dp_tmp_rep.aak_slo_trf g
ON a.accs_meth_id = g.accs_meth_id
AND a.file_dt = g.file_dt
AND f.call_start_dt = g.call_start_dt
LEFT JOIN dp_tmp_rep.aak_slo_sip h
ON a.accs_meth_id = h.accs_meth_id
AND a.file_dt = h.file_dt
AND f.call_start_dt = h.call_start_dt
LEFT JOIN dp_tmp_rep.aak_slo_rech i
ON a.accs_meth_id = i.accs_meth_id
AND a.file_dt = i.file_dt
AND f.call_start_dt = i.call_start_dt

GROUP BY 1,2,3
)
WITH DATA PRIMARY INDEX (Priceplan)







--Count of subs who have availed SLO offer before this one

SEL * FROM dp_tmp_rep.aak_slo_slo_availed
CREATE  TABLE dp_tmp_rep.aak_slo_slo_availed
AS
(
SEL
a.accs_meth_id
,a.file_dt Locking_Date
,CASE
WHEN b.offering_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Slo_Priceplan
,b.file_dt Previously_Availed_Date

FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN  dp_tmp_rep.aak_slo_pp b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.file_dt
LEFT JOIN dp_mdm_vew.adhoc_msisdn_load  c
ON a.accs_meth_id = c.accs_meth_id

WHERE c.file_dt < a.file_dt
AND campaign_file_desc = 'CAMP_SIM_LAGAO_DAILY'
GROUP BY 1,2,3,4
)
WITH DATA PRIMARY INDEX (accs_meth_id)
DEL FROM dp_tmp_rep.aak_slo_slo_availed WHERE Previously_Availed_Date IS NULL

--Getting Counts

CREATE  TABLE dp_tmp_rep.aak_slo_slo_availed2
AS
(
SEL 
v.accs_meth_id
,v.Locking_Date
,v.Slo_Priceplan
,v.Previous_Priceplan
,COUNT(*) AS SLO_Count
FROM
(
SEL
a.accs_meth_id
,Locking_Date
,Slo_Priceplan
,CASE
WHEN b.offrng_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Previous_Priceplan

FROM  dp_tmp_rep.aak_slo_slo_availed a
LEFT JOIN subscriber_hist b
ON a.accs_meth_id = b.accs_meth_id
WHERE row_type_cd <> 6
AND CAST(row_dt_tm AS DATE) < a.Previously_Availed_Date
QUALIFY ROW_NUMBER() OVER(PARTITION BY b.accs_meth_id ORDER BY row_dt_tm DESC)=1
)v
GROUP BY 1,2,3,4

)
WITH DATA PRIMARY INDEX (accs_meth_id)

SEL Locking_Date
,SLO_Priceplan
,Previous_Priceplan
,COUNT(DISTINCT accs_meth_id) AS Distinct_Subs
,COUNT(*)
 FROM  dp_tmp_rep.aak_slo_slo_availed2
 GROUP BY 1,2,3
 
--Dormancy

SEL * FROM dp_tmp_rep.aak_slo_slo_dorm
CREATE  TABLE dp_tmp_rep.aak_slo_slo_dorm
AS
(
SEL
a.accs_meth_id
,CASE
WHEN b.offering_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Slo_Priceplan
,a.file_dt
,days_since_last_activity
FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN  dp_tmp_rep.aak_slo_pp b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.file_dt
LEFT JOIN subscriber_dormancy c
ON a.accs_meth_id = c.accs_meth_id
WHERE dormancy_date = a.file_dt - 1
QUALIFY ROW_NUMBER() OVER(PARTITION BY c.accs_meth_id 
ORDER	BY days_since_last_activity ASC ) = 1
)
WITH DATA PRIMARY INDEX (accs_meth_id)

SEL
Slo_Priceplan
,file_dt
,CASE
WHEN days_since_last_activity >=0 AND days_since_last_activity<30 THEN 'A:0-30'
WHEN days_since_last_activity >=30 AND days_since_last_activity<40 THEN 'B:30-40'
WHEN days_since_last_activity >=40 AND days_since_last_activity<50 THEN 'C:40-50'
WHEN days_since_last_activity >=50 AND days_since_last_activity<60 THEN 'D:50-60'
WHEN days_since_last_activity >=60 AND days_since_last_activity<70 THEN 'E:60-70'
WHEN days_since_last_activity >=70 AND days_since_last_activity<80 THEN 'F:70-80'
WHEN days_since_last_activity >=80 AND days_since_last_activity<90 THEN 'G:80-90'
WHEN days_since_last_activity >=90 THEN 'H:>90'
END AS Dormancy_Band
,COUNT(*)
FROM dp_tmp_rep.aak_slo_slo_dorm
GROUP BY 1,2,3

--Migrations

SEL * FROM dp_tmp_rep.aak_slo_slo_mig
CREATE  TABLE dp_tmp_rep.aak_slo_slo_mig
AS
(
SEL
a.accs_meth_id
,CASE
WHEN b.offering_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Slo_Priceplan
,CASE
WHEN c.offrng_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Migration_Priceplan

FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN  dp_tmp_rep.aak_slo_pp b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.file_dt
LEFT JOIN subscriber_hist c
ON a.accs_meth_id = c.accs_meth_id

WHERE row_type_cd = 6
AND row_dt_tm > a.file_dt

QUALIFY ROW_NUMBER() OVER(PARTITION BY b.accs_meth_id ORDER BY row_dt_tm ASC)=1

)
WITH DATA PRIMARY INDEX (accs_meth_id)

SEL 
Slo_Priceplan
,Migration_Priceplan
,COUNT(*) 
FROM  dp_tmp_rep.aak_slo_slo_mig
GROUP BY 1,2

--Addons Usage

SEL * FROM  dp_tmp_rep.asp_sloreq_slo_addons
CREATE  TABLE dp_tmp_rep.asp_sloreq_slo_addons
AS
(
SEL
v.accs_meth_id
,v.prod_name
,SUM(v.Distinct_Subs)Distinct_Subs
,SUM(v.Subscription_Count)Subscription_Count
,SUM(v.Subscription_Rev)Subscription_Rev
FROM
(
SEL
accs_meth_id
,prod_name
,COUNT(DISTINCT accs_meth_id) Distinct_Subs
,COUNT(*) Subscription_Count
,SUM(unit_cost)Subscription_Rev
FROM sip_snapshot a
LEFT JOIN prod b
ON a.prod_id = b.prod_id
WHERE action = 'add' AND status = 'success'
AND created_date BETWEEN '2012-12-01' AND '2012-12-15'
AND accs_meth_id IN (SEL accs_meth_id FROM dp_tmp_rep.aak_slo_base GROUP BY 1)
GROUP BY 1,2

UNION ALL

SEL
accs_meth_id
,usage_type AS prod_name
,COUNT(DISTINCT accs_meth_id) Distinct_Subs
,COUNT(*) Subscription_Count
,SUM(amount)Subscription_Rev
FROM mediated_confrmtn_event
WHERE amount > 0
AND CAST(Confrmtn_Event_Start_Dt AS DATE) BETWEEN '2012-12-01' AND '2012-12-15'
AND accs_meth_id IN (SEL accs_meth_id FROM dp_tmp_rep.aak_slo_base GROUP BY 1)
GROUP BY 1,2
)v
GROUP BY 1,2
)
WITH DATA PRIMARY INDEX (accs_meth_id)

SEL
prod_name
,SUM(Distinct_Subs)
,SUM(Subscription_Count)
,SUM(Subscription_Rev)
FROM dp_tmp_rep.asp_sloreq_slo_addons
GROUP BY 1

--Revenue with Mins Banding

SEL * FROM dp_tmp_rep.aak_slo_fnl2
CREATE   TABLE dp_tmp_rep.aak_slo_fnl2
AS
(
SEL
CASE
WHEN b.offering_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Priceplan
,a.file_dt AS Locking_Date
,f.call_start_dt
,CASE
WHEN COALESCE(Total_Traffic_Mins,0) = 0 THEN '0'
WHEN COALESCE(Total_Traffic_Mins,0) >0 AND COALESCE(Total_Traffic_Mins,0) <=2 THEN '>0 AND <=2'
WHEN COALESCE(Total_Traffic_Mins,0) >2 AND COALESCE(Total_Traffic_Mins,0) <=5 THEN '>2 AND <=5'
WHEN COALESCE(Total_Traffic_Mins,0) >5 AND COALESCE(Total_Traffic_Mins,0) <=7 THEN '>5 AND <=7'
WHEN COALESCE(Total_Traffic_Mins,0) >7 AND COALESCE(Total_Traffic_Mins,0) <=10 THEN '>7 AND <=10'
WHEN COALESCE(Total_Traffic_Mins,0) >10 AND COALESCE(Total_Traffic_Mins,0) <=15 THEN '>10 AND <=15'
WHEN COALESCE(Total_Traffic_Mins,0) >15 AND COALESCE(Total_Traffic_Mins,0) <=20 THEN '>15 AND <=20'
WHEN COALESCE(Total_Traffic_Mins,0) >20 AND COALESCE(Total_Traffic_Mins,0) <=25 THEN '>20 AND <=25'
WHEN COALESCE(Total_Traffic_Mins,0) >25 AND COALESCE(Total_Traffic_Mins,0) <=30 THEN '>25 AND <=30'
WHEN COALESCE(Total_Traffic_Mins,0) >30 AND COALESCE(Total_Traffic_Mins,0) <=35 THEN '>30 AND <=35'
WHEN COALESCE(Total_Traffic_Mins,0) >35 AND COALESCE(Total_Traffic_Mins,0) <=40 THEN '>35 AND <=40'
WHEN COALESCE(Total_Traffic_Mins,0) >40 AND COALESCE(Total_Traffic_Mins,0) <=45 THEN '>40 AND <=45'
WHEN COALESCE(Total_Traffic_Mins,0) >45 AND COALESCE(Total_Traffic_Mins,0) <=50 THEN '>45 AND <=50'
WHEN COALESCE(Total_Traffic_Mins,0) >50 AND COALESCE(Total_Traffic_Mins,0) <=55 THEN '>50 AND <=55'
WHEN COALESCE(Total_Traffic_Mins,0) >55 THEN '>55'
END AS Overall_Mins_Band
,COUNT(DISTINCT a.accs_meth_id)Total_Subs
,COUNT(DISTINCT CASE WHEN g.Total_Traffic_Rev>0 OR g.Total_Traffic_Mins > 0 THEN g.accs_meth_id END ) AS Active_Subs

,SUM(g.Total_Traffic_Mins) Total_Traffic_Mins

-- revenues
,SUM(Charged_Onnet_Rev)Charged_Onnet_Rev
,SUM(UnCharged_Onnet_Rev)UnCharged_Onnet_Rev
,SUM(Regular_Offnet_Rev)Regular_Offnet_Rev
,SUM(IDD_Rev)IDD_Rev
,SUM(Charged_FNF_Rev)Charged_FNF_Rev
,SUM(UnCharged_FNF_Rev)UnCharged_FNF_Rev

,SUM(onnet_bundle_Rev)onnet_bundle_Rev
,SUM(offnet_bundle_Rev)offnet_bundle_Rev
,SUM(fnf_bundle_Rev)fnf_bundle_Rev
,SUM(idd_bundle_Rev)idd_bundle_Rev
,SUM(onnet_sms_Rev)onnet_sms_Rev
,SUM(offnet_sms_Rev)offnet_sms_Rev
,SUM(IDD_sms_Rev)IDD_sms_Rev
,SUM(bundle_sms_Rev)bundle_sms_Rev
,SUM(GPRS_rev)GPRS_rev

--volume
,SUM(Charged_Onnet_vol)Charged_Onnet_vol
,SUM(UnCharged_Onnet_vol)UnCharged_Onnet_vol
,SUM(Regular_Offnet_vol)Regular_Offnet_vol
,SUM(IDD_vol)IDD_vol
,SUM(Charged_FNF_vol)Charged_FNF_vol
,SUM(UnCharged_FNF_vol)UnCharged_FNF_vol

,SUM(onnet_bundle_vol)onnet_bundle_vol
,SUM(offnet_bundle_vol)offnet_bundle_vol
,SUM(fnf_bundle_vol)fnf_bundle_vol
,SUM(idd_bundle_vol)idd_bundle_vol
,SUM(onnet_sms_vol)onnet_sms_vol
,SUM(offnet_sms_vol)offnet_sms_vol
,SUM(IDD_sms_vol)IDD_sms_vol
,SUM(bundle_sms_vol)bundle_sms_vol
,SUM(GPRS_vol)GPRS_vol

-- number of calls
,SUM(Charged_Onnet_calls)Charged_Onnet_calls
,SUM(UnCharged_Onnet_calls)UnCharged_Onnet_calls
,SUM(Regular_Offnet_calls)Regular_Offnet_calls
,SUM(IDD_calls)IDD_calls
,SUM(Charged_FNF_calls)Charged_FNF_calls
,SUM(UnCharged_FNF_calls)UnCharged_FNF_calls

,SUM(onnet_bundle_calls)onnet_bundle_calls
,SUM(offnet_bundle_calls)offnet_bundle_calls
,SUM(fnf_bundle_calls)fnf_bundle_calls
,SUM(idd_bundle_calls)idd_bundle_calls
,SUM(onnet_sms_calls)onnet_sms_calls
,SUM(offnet_sms_calls)offnet_sms_calls
,SUM(IDD_sms_calls)IDD_sms_calls
,SUM(bundle_sms_calls)bundle_sms_calls


FROM dp_tmp_rep.aak_slo_base a
LEFT JOIN  dp_tmp_rep.aak_slo_pp b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.file_dt
LEFT JOIN dp_tmp_rep.aak_slo_un f
ON a.accs_meth_id = f.accs_meth_id
AND a.file_dt = f.file_dt
LEFT JOIN dp_tmp_rep.aak_slo_trf g
ON a.accs_meth_id = g.accs_meth_id
AND a.file_dt = g.file_dt
AND f.call_start_dt = g.call_start_dt

GROUP BY 1,2,3,4
)WITH DATA PRIMARY INDEX (Priceplan)

SEL COUNT(DISTINCT accs_meth_id) FROM  dp_tmp_rep.asp_sloreq_trf
WHERE COALESCE(Regular_Onnet_Mins,0) + COALESCE(Regular_Offnet_Mins,0) > 5

--base for tracking

SEL * FROM dp_tmp_rep.asp_sloreq_base2
CREATE  TABLE dp_tmp_rep.asp_sloreq_base2
AS
(
SEL
accs_meth_id
,file_dt
FROM dp_mdm_vew.adhoc_msisdn_load 
WHERE campaign_file_desc = 'CAMP_SIM_LAGAO_DAILY'
AND file_dt BETWEEN '2012-11-22' AND '2012-12-21'
GROUP BY 1,2
)
WITH DATA PRIMARY INDEX (accs_meth_id)

--Getting Priceplan

SEL * FROM  dp_tmp_rep.asp_sloreq_pp2
CREATE  TABLE dp_tmp_rep.asp_sloreq_pp2
AS
(
SEL
a.accs_meth_id
,file_dt
,CASE
WHEN b.offering_id IN (8	,67	,110	,112	,137	,138	,142, 169) THEN 'DJ'
ELSE 'TS' END AS Slo_Priceplan
FROM dp_tmp_rep.asp_sloreq_base2 a
LEFT JOIN call_hist b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.call_start_dt
WHERE call_start_dt BETWEEN '2012-11-22' AND '2012-12-21'
QUALIFY ROW_NUMBER() OVER(PARTITION BY b.accs_meth_id ORDER BY call_start_dt DESC)=1
)
WITH DATA PRIMARY INDEX (accs_meth_id)

SEL * FROM  dp_tmp_rep.asp_sloreq_trf3
CREATE  TABLE dp_tmp_rep.asp_sloreq_trf3
AS
(
SEL
v.accs_meth_id
,v.file_dt
,v.tracking_date
,SUM(v.Total_Rev) Total_Rev
,SUM(v.Total_mins)Total_mins
FROM
(
SEL
a.accs_meth_id
,a.file_dt
,call_start_dt AS tracking_date
,COALESCE(SUM(call_gross_revenue_amt),0) AS Total_Rev
,COALESCE(SUM(call_network_vol),0) AS Total_mins
FROM dp_tmp_rep.asp_sloreq_pp2 a
LEFT JOIN call_hist b
ON a.accs_meth_id = b.accs_meth_id
WHERE call_start_dt BETWEEN  '2012-11-22' AND '2012-12-21'
AND Slo_Priceplan = 'TS'
GROUP BY 1,2,3

UNION ALL

SEL
a.accs_meth_id
,a.file_dt
,created_date AS tracking_date
,COALESCE(SUM(unit_cost),0) AS Total_Rev
,0 AS Total_mins
FROM dp_tmp_rep.asp_sloreq_pp2 a
LEFT JOIN sip_snapshot b
ON a.accs_meth_id = b.accs_meth_id
WHERE created_date BETWEEN  '2012-11-22' AND '2012-12-21'
AND action = 'add' AND status = 'success'
AND Slo_Priceplan = 'TS'
GROUP BY 1,2,3

UNION ALL

SEL
a.accs_meth_id
,a.file_dt
,CAST(Confrmtn_Event_Start_Dt AS DATE) AS tracking_date
,COALESCE(SUM(amount),0) AS Total_Rev
,0 AS Total_mins
FROM dp_tmp_rep.asp_sloreq_pp2 a
LEFT JOIN mediated_confrmtn_event b
ON a.accs_meth_id = b.accs_meth_id
WHERE CAST(Confrmtn_Event_Start_Dt AS DATE) BETWEEN  '2012-11-22' AND '2012-12-21'
AND amount > 0
AND Slo_Priceplan = 'TS'
GROUP BY 1,2,3
)v

GROUP BY 1,2,3
)
WITH DATA PRIMARY INDEX (accs_meth_id)

--Tracking

SEL * FROM dp_tmp_rep.asp_sloreq_tracking
WHERE tracking_date IS NOT NULL
ORDER BY 1,2
CREATE  TABLE dp_tmp_rep.asp_sloreq_tracking
AS
(
SEL
a.file_dt
,b.tracking_date
,SUM(CASE WHEN Total_Rev > 0 OR Total_mins > 0 THEN 1 ELSE 0 END) AS Active_Subs_Count


FROM dp_tmp_rep.asp_sloreq_base2 a
LEFT JOIN dp_tmp_rep.asp_sloreq_trf3 b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.file_dt

GROUP BY 1,2
)
WITH DATA PRIMARY INDEX (file_dt)

--For DJ

CREATE  TABLE dp_tmp_rep.asp_sloreq_trf4
AS
(
SEL
v.accs_meth_id
,v.file_dt
,v.tracking_date
,SUM(v.Total_Rev) Total_Rev
,SUM(v.Total_mins)Total_mins
FROM
(
SEL
a.accs_meth_id
,a.file_dt
,call_start_dt AS tracking_date
,COALESCE(SUM(call_gross_revenue_amt),0) AS Total_Rev
,COALESCE(SUM(call_network_vol),0) AS Total_mins
FROM dp_tmp_rep.asp_sloreq_pp2 a
LEFT JOIN call_hist b
ON a.accs_meth_id = b.accs_meth_id
WHERE call_start_dt BETWEEN  '2012-11-22' AND '2012-12-21'
AND Slo_Priceplan = 'DJ'
GROUP BY 1,2,3

UNION ALL

SEL
a.accs_meth_id
,a.file_dt
,created_date AS tracking_date
,COALESCE(SUM(unit_cost),0) AS Total_Rev
,0 AS Total_mins
FROM dp_tmp_rep.asp_sloreq_pp2 a
LEFT JOIN sip_snapshot b
ON a.accs_meth_id = b.accs_meth_id
WHERE created_date BETWEEN  '2012-11-22' AND '2012-12-21'
AND action = 'add' AND status = 'success'
AND Slo_Priceplan = 'DJ'
GROUP BY 1,2,3

UNION ALL

SEL
a.accs_meth_id
,a.file_dt
,CAST(Confrmtn_Event_Start_Dt AS DATE) AS tracking_date
,COALESCE(SUM(amount),0) AS Total_Rev
,0 AS Total_mins
FROM dp_tmp_rep.asp_sloreq_pp2 a
LEFT JOIN mediated_confrmtn_event b
ON a.accs_meth_id = b.accs_meth_id
WHERE CAST(Confrmtn_Event_Start_Dt AS DATE) BETWEEN  '2012-11-22' AND '2012-12-21'
AND amount > 0
AND Slo_Priceplan = 'DJ'
GROUP BY 1,2,3
)v

GROUP BY 1,2,3
)
WITH DATA PRIMARY INDEX (accs_meth_id)

SEL * FROM dp_tmp_rep.asp_sloreq_tracking2
WHERE tracking_date IS NOT NULL
ORDER BY 1,2
CREATE  TABLE dp_tmp_rep.asp_sloreq_tracking2
AS
(
SEL
a.file_dt
,b.tracking_date
,SUM(CASE WHEN Total_Rev > 0 OR Total_mins > 0 THEN 1 ELSE 0 END) AS Active_Subs_Count


FROM dp_tmp_rep.asp_sloreq_base2 a
LEFT JOIN dp_tmp_rep.asp_sloreq_trf4 b
ON a.accs_meth_id = b.accs_meth_id
AND a.file_dt = b.file_dt

GROUP BY 1,2
)
WITH DATA PRIMARY INDEX (file_dt)



